### ISSUE TITLE
How to we configure it with ssl ?

### ISSUE THREAD

**Issue by thapakazi** [percona/mongodb_exporter#18]
I just wonder how we could configure it with ssl options ?

Also isn't this exporting compatible with rocksdb :cold_sweat: ?

**Comment by timvaillancourt** [comment]
We plan on adding both SSL and RocksDB support in the near future, however both are not currently supported.

I plan to integrate this commit (from another fork of this project) to add SSL/TLS support when I have time: https://github.com/dcu/mongodb_exporter/commit/bdb7e63da972827b9f8309301f2d8709ef4f6fe5#diff-1f9168f6e0298b80c03b2fee77eb8c84

RocksDB support is coming in a new branch in the next few days.

**Comment by dbmurphy** [comment]
@timvaillancourt  We should not have SSL support as the exporter should be running locally on each mongod box. Instead, we are adding SSL  support to PMM  so that  Prometheus <-> Exporters will be SSL enabled.

**Comment by timvaillancourt** [comment]
We plan to implement #40 soon, closing this issue. Also #35 added Prometheus => mongodb_export SSL support.
