### ISSUE TITLE
Create OCI image for mongodb_exporter and update helm chart.

### ISSUE THREAD

**Issue by askomorokhov** [percona/mongodb_exporter#265]
https://github.com/prometheus-community/helm-charts/blob/main/charts/prometheus-mongodb-exporter/values.yaml#L16-L17

**Comment by kbudde** [comment]
Hi,

I can prepare a github workflow to create and upload a container image to dockerhub with goreleaser.
I just need to know which namespace to use:
- e.g. percona/mongodb_exporter

You need to create two secrets:
- DOCKERHUB_USERNAME, e.g. percona
- DOCKERHUB_TOKEN, see https://docs.docker.com/docker-hub/access-tokens/

If you want to use a different namespace or some other provider, e.g. quay.io, just tell me.

**Comment by ShashankSinha252** [comment]
OCI image for MongoDB exporter has been created. Helm chart is pending.

**Comment by denisok** [comment]
https://github.com/prometheus-community/helm-charts/pull/2108

**Comment by ShashankSinha252** [comment]
Helm charts work is also done. Thanks @monotek
