### ISSUE TITLE
Why many metrics don't have member label ?

### ISSUE THREAD

**Issue by baiwfg2** [percona/mongodb_exporter#266]
Hi. I start one mongodb_exporter to scrape metrics of a replica set with 3 nodes. But I cannot extract `member` label from many metrics, such as:

`mongodb_ss_wt_block_manager_blocks_read{cl_id="6098d5af91ec5fad8a3c96d7",cl_role="shardsvr",rs_nm="shard1",rs_state="1"} 3773`

I thought the member of a replica set was included in metrics such that we can group it by different members.

Should I deploy one mongodb_exporter per mongod/mongos instead of only one mongodb_exporter instance ?
Maybe mongodb_exporter needs have a `--discover` option like the one in mongostat ?

**Comment by baiwfg2** [comment]
When I run command like this: 

`mongodb_exporter --mongodb.uri=mongodb://admin:123456@9.134.5.74:30002,9.134.5.74:30001,9.134.5.74:30003/admin`

It still only scrapes primary node , why is that ?

**Comment by percona-csalguero** [comment]
> When I run command like this:
> 
> `mongodb_exporter --mongodb.uri=mongodb://admin:123456@9.134.5.74:30002,9.134.5.74:30001,9.134.5.74:30003/admin`
> 
> It still only scrapes primary node , why is that ?

It only scrapes primary because the exporter use direct connection to the first server in the list to be able to get replicaset information.
Maybe it would be a good enhancement to make it able to detect there are more that one server in the list and make it connect (using direct connection) to all of them.

**Comment by baiwfg2** [comment]
I have interest to implement this if possible.

**Comment by percona-csalguero** [comment]
Regarding the other question, the only [topology labels](https://github.com/percona/mongodb_exporter/blob/main/exporter/topology_info.go#L34-L37) applied to all metrics are: 
```
	labelClusterRole     = "cl_role"
	labelClusterID       = "cl_id"
	labelReplicasetName  = "rs_nm"
	labelReplicasetState = "rs_state"
```
The `member_idx` is only applied if `name` appears as part of a [data tree](https://github.com/percona/mongodb_exporter/blob/main/exporter/metrics.go#L315-L318).
```
		// use the replicaset or server name as a label
		if name, ok := s["name"].(string); ok {
			labels["member_idx"] = name
		}
		if state, ok := s["stateStr"].(string); ok {
			labels["member_state"] = state
		}
```
Please, fill free to create new [Jira](https://jira.percona.com/projects/PMM/issues) tickets or we can talk on our community [Discord](https://discord.gg/hQBrHgGX).
Regards
