### ISSUE TITLE
Grafana Dashboard ?

### ISSUE THREAD

**Issue by binhvcom** [percona/mongodb_exporter#281]
Do we have a offical grafana dashboard is that work with the latest version ?

**Comment by odederner1** [comment]
Hi,
Latest dashboards from: https://github.com/percona/grafana-dashboards  (MongoDB)
should work with latest exporter? or should we use --compatible-mode and --discovering-mode ???
What is the correct march between mongodb-exporter and the above dashboards?

**Comment by feelan03** [comment]
Is there any progress on this issue? How can I use this dashboard?

**Comment by adivinho** [comment]
Latest versions of dashboards are located here
https://github.com/percona/grafana-dashboards/tree/PMM-2.0/dashboards
It's recommended to use flag _--compatible-mode_ for exporter.

**Comment by binhvcom** [comment]
Hello,

I’m sorry for the late reply
Thanks for your support, the dashboard is working perfect for me.
