### ISSUE TITLE
Is there any document about metrics?

### ISSUE THREAD

**Issue by max-tian** [percona/mongodb_exporter#284]
I would like to know some detail information about every metrics. Can somebody provide documentation about metrics?

**Comment by percona-csalguero** [comment]
MongoDB exporter grabs **ALL** fields by traversing the output of `getDiagnosticData` and expose all numeric fields.
You can read more about it [here](https://www.percona.com/blog/2020/09/22/new-mongodb-exporter-released-with-percona-monitoring-and-management-2-10-0/)

**Comment by percona-csalguero** [comment]
Just a comment with more info:
Please check [MongoDB Diagnostic commands](https://docs.mongodb.com/manual/reference/command/nav-diagnostic/) information page to get more info about metrics as `getDiagnosticData` seems to be collecting information from all sources.

**Comment by AxelUser** [comment]
Hi, may you please assist, does this command work when connected to mongos? In my case exporter return no such metrics for router, while for data-carrying nodes it return metrics.

I've also tried to run `db.runCommand({getDiagnosticData: 1})` on router and on secondary, and for router is also returns empty data, while for secondary returns object with all that fields.

Then I've run `db.runCommand({serverStatus: 1})` on router and it returns [serviceStatus metrics](https://www.mongodb.com/docs/manual/reference/command/serverStatus/#definition).

I couldn't find any docs about getDiagnosticData command, but if it doesn't work for routers, then maybe exporter should traverse all commands from [this list](https://www.mongodb.com/docs/manual/reference/command/nav-diagnostic/)?

Does it work for your setup?

**Comment by AxelUser** [comment]
Seems like this command is only for mongod processes, is I understood [this comment](https://github.com/mongodb/mongo/blob/master/src/mongo/s/commands/cluster_ftdc_commands.cpp#L45) correctly. Is it a good idea to implement fallback for mongos?

**Comment by kevincantu** [comment]
IMHO a missing bit of documentation is as follows.   From Prometheus you can lookup metadata about specific metrics using this API (here via Grafana):
https://prometheus.io/docs/prometheus/latest/querying/api/#querying-target-metadata

```
curl -fsSLk \
  ...
  --header "Content-Type:application/json" \
  "${grafana_host}/api/datasources/proxy/1/api/v1/targets/metadata" \
  --get \
  --data-urlencode 'metric=mongodb_top_queries_time' \
  | jq
```

And that returns a terse summary showing that for this one it's `top.queries.`, which you can find more detail on here in Mongo docs, for example:
https://www.mongodb.com/docs/manual/reference/command/top/
