### ISSUE TITLE
Log rotate ??

### ISSUE THREAD

**Issue by mg03** [percona/mongodb_exporter#29]
Hi

I see it rotates logs as I can see a bunch of logs like below and thats good. But is there a setting not only to rotate but to delete old log files?

-rw-r--r-- 1 prometheus iptvgrp     193 Oct 26 18:45 mongodb_exporter.ip-10-113-198-204.unknownuser.log.ERROR.20161026-184537.3156
-rw-r--r-- 1 prometheus iptvgrp     193 Oct 26 18:45 mongodb_exporter.ip-10-113-198-204.unknownuser.log.INFO.20161026-184537.3207
-rw-r--r-- 1 prometheus iptvgrp     193 Oct 26 18:45 mongodb_exporter.ip-10-113-198-204.unknownuser.log.WARNING.20161026-184548.3207
-rw-r--r-- 1 prometheus iptvgrp     193 Oct 26 18:45 mongodb_exporter.ip-10-113-198-204.unknownuser.log.ERROR.20161026-184548.3207
lrwxrwxrwx 1 prometheus iptvgrp      79 Oct 26 18:45 mongodb_exporter.WARNING -> mongodb_exporter.ip-10-113-198-204.unknownuser.log.WARNING.20161026-184548.3207
lrwxrwxrwx 1 prometheus iptvgrp      77 Oct 26 18:45 mongodb_exporter.ERROR -> mongodb_exporter.ip-10-113-198-204.unknownuser.log.ERROR.20161026-184548.3207
lrwxrwxrwx 1 prometheus iptvgrp      76 Oct 26 18:45 mongodb_exporter.INFO -> mongodb_exporter.ip-10-113-198-204.unknownuser.log.INFO.20161026-184548.3238

**Comment by timvaillancourt** [comment]
Good point, I'll look into a solution or will eventually add a logrotated sample config to use for rotation/compression of logs.

**Comment by AlekSi** [comment]
In v0.2.0 logs are written to stderr.
