### ISSUE TITLE
Support `compatible-mode` for `indexstats`

### ISSUE THREAD

**Issue by gg-kialo** [percona/mongodb_exporter#297]
The `compatible-mode` switch is ignored in [`indexstats_collector.go`](https://github.com/percona/mongodb_exporter/blob/main/exporter/indexstats_collector.go#L93). This produces unique metrics names, containing the db, collection, and index name, for which dashboards and alerts are hard to produce.

By supporting `compatible-mode` and using a single metric name, with the db, collection, and index name as labels on the metric (as in the pre-0.20 releases), it will make it much easier to include in dashboards.

e.g. instead of a metric `mongodb_collstats_storageStats_indexSizes_some_index_name`, a metric `mongodb_collstats_storageStats_indexSizes` with a label `key_name=some_index_name` should be used instead. This would match how `mongodb_indexstats_accesses_ops` is used.

**Comment by zekena2** [comment]
any updates on this??

**Comment by BupycHuk** [comment]
Hi, it was implemented and will be released in v0.43.0
