### ISSUE TITLE
No metrics for mongos

### ISSUE THREAD

**Issue by gaantunes** [percona/mongodb_exporter#307]
I am using [percona grafana dashboards](https://github.com/percona/grafana-dashboards/tree/PMM-2.0/dashboards) with the test cluster that runs with the docker-compose file included in this repo. Every instance gets data collected, but mongos does not collect most of the data.

Seems like it's trying to collect using `diagnosticDataCollector` but the `getDiagnosticData` command doesn't return anything. Looks like the right method to collect data for mongos would be with `serverStatusCollector`, which returns all the data needed, such as opCounters and others, but this collector is not being called by the exporter.

Is this expected behaviour?

**Comment by KeithTt** [comment]
I create a sharded cluster, and also found that there is no metrics for mongos, I got `server returned HTTP status 500 Internal Server Error`.

Maybe this exporter only works for mongod instance?

**Comment by ozkar2c** [comment]
Hi guys

Do you know if there are equivalent metrics for these old ones?

mongodb_mongos_sharding_databases_total
mongodb_mongos_sharding_collections_total
mongodb_mongos_sharding_shards_total
mongodb_mongos_sharding_chunks_total
mongodb_mongos_sharding_balancer_enabled
mongodb_mongos_sharding_chunks_is_balanced

Thanks a lot

**Comment by percona-csalguero** [comment]
Hello, in compatibility mode and when connected to a mongos, you should have those metrics.
Check https://github.com/percona/mongodb_exporter/blob/main/exporter/v1_compatibility.go#L113 and if you found something wrong (it might be possible) please create a ticket in our [Jira](https://jira.percona.com/projects/PMM/issues/PMM-8094?filter=allopenissues)
I will be glad to fix any issue.

Regards.
