### ISSUE TITLE
 questions about metrics for several bases

### ISSUE THREAD

**Issue by thedje** [percona/mongodb_exporter#312]
Hi,

I have a mongodb instance on a server1 containing only one base and I have metrics with the label rs_nm the name of the base:
ex: mongodb_sys_netstat_Tcp_RtoAlgorithm {cl_id = "608921f272bce3bb425f7d16", cl_role = "shardsvr", rs_nm = "<_base name_>", rs_state = "1"} 1

I have another instance on a server2 containing several bases and there I do not have the base label:
mongodb_sys_netstat_Tcp_RtoAlgorithm {cl_id = "", cl_role = "mongod", rs_state = "0"} 1

How should I configure the export to get this kind of info?

For server2 I have the following variables:
MONGODB_URI: mongodb: // <_user_>: <_psswd_> @ <_host_>: 27017 / admin? AuthSource = admin

my command line: --web.telemetry-path = / metrics --mongodb.direct-connect = false

Second question: what metric can I use to see the state (up or down) of my base (s)?

**Comment by percona-csalguero** [comment]
Is server2 part of a replicaset or it is an standalone instance?
`rs_nm` is the replicaset name. If server2 is a standalone instance, you won't have a value for that label.

**Comment by thedje** [comment]
It's an standalone instance.

Ok. So, what metric can I use to see the state (up or down) of my base (s)?

**Comment by percona-csalguero** [comment]
If I understand correctly what you need, when [PR #322](https://github.com/percona/mongodb_exporter/pull/322/files) is merged you will be able to use the `rs_state` label.
