### ISSUE TITLE
Prometheus exporter continues to export after database has been dropped

### ISSUE THREAD

**Issue by msmerc** [percona/mongodb_exporter#313]
Hi,

I've noticed that if we remove a mongo database the exporter will still retain all its metrics. I've not tested to see what happens if we drop a collection - but it's probably the same.

We find our dev server ends up with lots of dead metrics as a result. Might it be possible to enhance the exporter so that it forgets about collections after they are removed?

**Comment by percona-csalguero** [comment]
I cannot reproduce the issue.
I've created a new [branch and a PR](https://github.com/percona/mongodb_exporter/pull/323) with a test case. Please fill free to change it to make it prove the issue. 

Thanks

**Comment by percona-csalguero** [comment]
Closing due to no response. I am assuming this cannot be reproduced.
