### ISSUE TITLE
Add config option to restrict collection to specific databases

### ISSUE THREAD

**Issue by msmerc** [percona/mongodb_exporter#314]
Right now you can configure the exporter to monitor specific collections, but this is verbose if you want to monitor all the collections but only in a certain database.

Would we add an option to specify the databases to monitor and the exporter could discover all the collections within that database?

**Comment by yaron** [comment]
you can use wildcards to select all collections in a database.
This worked for me to get metrics on all collections in the "yaron" database:
`--mongodb.collstats-colls=yaron.* --mongodb.indexstats-colls=yaron.*"`
Maybe this needs to be added to the documentation, but I think this solves the ticket, or am I missing something?
