### ISSUE TITLE
List all the metrics without a MongoDB install

### ISSUE THREAD

**Issue by vishal-h** [percona/mongodb_exporter#317]
Is it possible to list all the metrics emitted by mongodb_exporter without actually running an instance/replicaset of mongo?

I am going over the code to see if it's feasible but can't find any. 

For example if I need all the rs metrics, like mongodb_rs_*, what do I do?

Thanks for any inputs

**Comment by vishal-h** [comment]
Or $collStats related metrics etc

**Comment by PaulJacobs-percona** [comment]
Hi @vishal-h Thanks for your question. It's not possible to discover available metrics without connecting to an instance. Can you explain more about what you're trying to do? Maybe we can come up with another solution. (Alternatively, come along to our next exporters community meeting to explain in person. If you're interested, let me know and I'll share the details with you.)

**Comment by vishal-h** [comment]
I've a stand-alone mongodb instance in our sandbox environment and have wired up prometheus/mongodb_exporter. I was in the process of setting up a rs, but then started looking for a shortcut. It's a nice feature to have though.
