### ISSUE TITLE
exporter increase logicalSessionRecordCache.activeSessionsCount

### ISSUE THREAD

**Issue by laurent6** [percona/mongodb_exporter#318]
Hi, 

The exporter increase   indefinitely logicalSessionRecordCache.activeSessionsCount
I already add the following configuration: 
`setParameter:
  logicalSessionRefreshMillis: 120000
  localLogicalSessionTimeoutMinutes: 15
`
but still increase connection. When I stop exporter the logicalSessionRecordCache stop to increase. 
I use mongo 4.4.5
what's happens and how can I solve it ?  

Thanks

**Comment by percona-csalguero** [comment]
Hi, 

This metrics is not something the mongo exporter "do".
The driver handles the connections pool automatically and AFAIK, there is nothing we can do.
I tried limiting the number of connections the driver will keep open by setting `maxPoolSize` in the URI as 
```
./mongodb_exporter --mongodb.uri=mongodb://127.0.0.1:17001/admin?maxPoolSize=1
``` 
but `mongodb_ss_logicalSessionRecordCache_activeSessionsCount` is still being increased on every request. 

Here you can read more about [connection pooling in the MongoDB Go driver](https://blog.mlab.com/2013/11/deep-dive-into-connection-pooling/)

Regards
