### ISSUE TITLE
Exporter process uses more CPU than expected

### ISSUE THREAD

**Issue by timvaillancourt** [percona/mongodb_exporter#32]
This is to track a  low priority investigation into what consumes CPU in our exporter. In one instance of mongodb_exporter running under Percona Monitoring and Management (same exporter code) I can see it use 5-6% user-level CPU at all times.

An example:
```
$ ps aux|grep mongodb_exporter|grep -v grep
root      7666  5.4  0.4  23756 18224 ?        Sl   Nov06 727:30 /usr/local/percona/pmm-client/mongodb_exporter ...
```

Maybe this is CPU usage is normal but it would be good to make sure we aren't doing anything silly to cause this.

**Comment by percona-csalguero** [comment]
Please let me know if I can help.
Meanwhile, this article can be helpful: https://blog.golang.org/profiling-go-programs

**Comment by timvaillancourt** [comment]
Hey @percona-csalguero, tried using pprof but somehow my profile is always empty.

I tried putting it in here: https://github.com/Percona-Lab/prometheus_mongodb_exporter/blob/master/mongodb_exporter.go#L111 and even here: https://github.com/Percona-Lab/prometheus_mongodb_exporter/blob/master/collector/mongodb_collector.go#L51.

I'm guessing this has something to do with channels but I didn't have any time to dig in.

**Comment by timvaillancourt** [comment]
Closing, will keep in mind and will re-open in PMM Jira later.
