### ISSUE TITLE
Any plan to release the mongodb exporter from release-0.1x branch

### ISSUE THREAD

**Issue by chadr123** [percona/mongodb_exporter#324]
Do you have any plan to release the mongodb exporter from release-0.1x branch? Because there are several improvements but it is still not released.

**Comment by denisok** [comment]
Hi @chadr123, any reasons to not use not version ?

**Comment by chadr123** [comment]
> Hi @chadr123, any reasons to not use not version ?

@denisok Hi, I could not use the latest version of the mongodb exporter which starts with 0.2x due to following issues.
 - https://jira.percona.com/browse/PMM-7947
 - https://jira.percona.com/browse/PMM-7424

**Comment by denisok** [comment]
PMM-7947 looks to be solved: #322 ?

**Comment by chadr123** [comment]
> [PMM-7947](https://jira.percona.com/browse/PMM-7947) looks to be solved: #322 ?

Thank you for your reply.

I didn't check whether #322 fixes the PMM-7947. But the actual problem is that the mongodb exporter did not collect much metrics for the `mongos`.
So, if the mongodb exporter collect metrics which following dashboard queries metrics, that is fine.
 - QPS of Mongos Service in the MongoDB Cluster Summary
 - All fields in the MongoDB Instances Overview with specific Node Name that has mongos’s node name

**Comment by chadr123** [comment]
> [PMM-7424](https://jira.percona.com/browse/PMM-7424) is probably #329

Yeah. I expect that #329 could resolve the PMM-7424. :)

**Comment by denisok** [comment]
> > Hi, #329 have been merged.
> > Notice that the metric names now have a prefix `mongodb_dbstat`.
> 
> Thank you so much! But actually I want the compatible mode for dbstat because we are depending on the old style of the metrics name at the moment. I will wait for the compatible mode for dbstat. Anyway thanks again your efforts!

should be fixed here: https://github.com/percona/mongodb_exporter/issues/336
