### ISSUE TITLE
hello cannot use

### ISSUE THREAD

**Issue by chdanandaroopaha** [percona/mongodb_exporter#33]
go build -o mongodb_exporter github.com/Percona-Lab/prometheus_mongodb_exporter

It gives -- cannot find package "gopkg.in/mgo.v2" in any of:
	/home/devops/go/src/github.com/Percona-Lab/prometheus_mongodb_exporter/vendor/gopkg.in/mgo.v2 (vendor tree)

we have to get package with all dependencies than I tired

 go get github.com/Percona-Lab/prometheus_mongodb_exporter 
than

Cloning into '/home/devops/go/src/gopkg.in/mgo.v2'...
error: RPC failed; curl 56 GnuTLS recv error (-9): A TLS packet with unexpected length was received.

How can we solve this issue.

Thanks

**Comment by percona-csalguero** [comment]
use `govendor sync` to update your dependencies.

**Comment by timvaillancourt** [comment]
Closing this issue, please re-open if:

go get -d github.com/percona/mongodb_exporter
cd $GOPATH/src/github.com/percona/mongodb_exporter
govendor sync
go build -o mongodb_exporter mongodb_exporter.go

Does not work.
