### ISSUE TITLE
TLS not working correctly: tlsCertificateKeyFile not sending intermediate(s)

### ISSUE THREAD

**Issue by whiemstra** [percona/mongodb_exporter#335]
In the 0.10.x, 0.11.x and 0.20.x versions using TLS works not as expected. Since version 0.10.x the `--mongodb.tls-cert` was replaced with the connection string option `tlsCertificateKeyFile`. When using a public and private certificate and also a chain of intermediates (all in the same pem file) the chain of intermediates is not send to the MongoDB instance and the connection will fail, which did not fail with `--mongodb.tls-cert` was available.

In version **0.11.2** the logging shows:
`INFO[0000] Starting mongodb_exporter (version=, branch=, revision=)  source="mongodb_exporter.go:81"
INFO[0000] Build context (go=go1.15.2, user=, date=19700101-01:00:00)  source="mongodb_exporter.go:82"
ERRO[0000] Can't create mongo session to mongodb://****  source="mongodb_collector.go:188"
INFO[0000] Starting HTTP server for http://:9216/metrics ...  source="server.go:140"`

Metrics page does not show an error.

In version **0.20.7** the logging shows:
`INFO[0000] Starting HTTP server for http://:9216/metrics ...  source="server.go:140"
ERRO[0009] Cannot connect to MongoDB: tls: private key does not match public key`

Metrics page shows error:
`An error has occurred while connecting to MongoDB:
`
`tls: private key does not match public key`

In the older version **0.9.x** it was possible to set --mongodb.tls-cert which works as expected. The intermediates are also send to the MongoDB instance.

**Comment by ShashankSinha252** [comment]
We plan to release a new version of MongoDB exporter soon @mukerjee . Please check out [0.31.0](https://github.com/percona/mongodb_exporter/milestone/8) for updates on our progress for new release.

**Comment by mukerjee** [comment]
Unfortunately we're not using mongodb in our project anymore so i don't have a quick way to check this. I would assume it's fixed though on a new release, because it worked for me before as long as I had commit a24ec48a9bd6fc6275deae50f25740c446fb4512
