### ISSUE TITLE
Missing old metrics for dbStats

### ISSUE THREAD

**Issue by kanakagrawal** [percona/mongodb_exporter#336]
I ran the latest main branch with the following command on mongod instance - 
```
./mongodb_exporter --mongodb.uri=mongodb://127.0.0.1:17001 --compatible-mode
```

On checking metrics, there are no metrics for `mongodb_mongod_db_*`
```bash
root@linux:~# curl http://127.0.0.1:9216/metrics | grep mongodb_mongod_db
root@linux:~# 
```

If I run the binary from `release-0.1x` branch, we get these metrics - 
```
root@linux:~# curl http://127.0.0.1:9216/metrics | grep mongodb_mongod_db
# HELP mongodb_mongod_db_collections_total Contains a count of the number of collections in that database
# TYPE mongodb_mongod_db_collections_total gauge
mongodb_mongod_db_collections_total{db="admin"} 1
mongodb_mongod_db_collections_total{db="config"} 1
mongodb_mongod_db_collections_total{db="local"} 7
# HELP mongodb_mongod_db_data_size_bytes The total size in bytes of the uncompressed data held in this database
# TYPE mongodb_mongod_db_data_size_bytes gauge
mongodb_mongod_db_data_size_bytes{db="admin"} 221
mongodb_mongod_db_data_size_bytes{db="config"} 0
mongodb_mongod_db_data_size_bytes{db="local"} 5450
# HELP mongodb_mongod_db_index_size_bytes The total size in bytes of all indexes created on this database
# TYPE mongodb_mongod_db_index_size_bytes gauge
mongodb_mongod_db_index_size_bytes{db="admin"} 32768
mongodb_mongod_db_index_size_bytes{db="config"} 4096
mongodb_mongod_db_index_size_bytes{db="local"} 98304
# HELP mongodb_mongod_db_indexes_total Contains a count of the total number of indexes across all collections in the database
# TYPE mongodb_mongod_db_indexes_total gauge
mongodb_mongod_db_indexes_total{db="admin"} 1
mongodb_mongod_db_indexes_total{db="config"} 1
mongodb_mongod_db_indexes_total{db="local"} 6
# HELP mongodb_mongod_db_objects_total Contains a count of the number of objects (i.e. documents) in the database across all collections
# TYPE mongodb_mongod_db_objects_total gauge
mongodb_mongod_db_objects_total{db="admin"} 2
mongodb_mongod_db_objects_total{db="config"} 0
mongodb_mongod_db_objects_total{db="local"} 27
root@linux:~# 
```

With `--compatible-mode` set, old metrics should be available. I added a comment for this [here](https://github.com/percona/mongodb_exporter/pull/329#issuecomment-903384401) but that PR is merged.

So, I'm creating a new issue to track this.

**Comment by kanakagrawal** [comment]
Consider the following dbstats metric - `mongodb_dbstats_testdb_indexSize{cl_id="611fa5e6165e2964515910a7",cl_role="shardsvr",rs_nm="rs1",rs_state="1"} 49152`

In old metrics, this would have been - `mongodb_mongod_db_index_size_bytes{db="testdb"} 49152`

To transform such metric into its old metric format is not simple as name of database(`testdb` in this example) is part of the metric name. There is no implementation in the current code for such metric conversion. One way to solve this problem is to remove name of database from the metric and keep it only in the labels. With this we can simply create a `conversion` object specifying `oldName` and `newName` like this - 
```golang
		{
			oldName: "mongodb_mongod_db_index_size_bytes",
			newName: "mongodb_dbstats_indexSize",
		},
```

I've created a draft PR with this approach: #337 
**This approach will modify the metrics and remove database names from it.** For example, `mongodb_dbstats_testdb_indexSize{cl_id="611fa5e6165e2964515910a7",cl_role="shardsvr",rs_nm="rs1",rs_state="1"} 49152` will be changed to `mongodb_dbstats_indexSize{cl_id="611fa5e6165e2964515910a7",cl_role="shardsvr",database="testdb",rs_nm="rs1",rs_state="1"} 49152`


@percona-csalguero is this solution acceptable?

**Comment by percona-csalguero** [comment]
It looks good to me. 
Thanks
