### ISSUE TITLE
copying image to another server and starting mongo-exporter

### ISSUE THREAD

**Issue by TamarNR** [percona/mongodb_exporter#369]
Hi,

I am getting this error trying to run the container:
`docker run --name mongodb-exporter -p 9216:9216 --env "MONGODB_URI=mongodb://myadminuser:oct-%2B2020@11.9.1.13:27000/?replicaSet=octopusrs0&authSource=admin" bitnami/mongodb-exporter:latest`

```
time="2021-10-18T08:25:48Z" level=info msg="Starting mongodb_exporter (version=, branch=, revision=)" source="mongodb_exporter.go:81"
time="2021-10-18T08:25:48Z" level=info msg="Build context (go=go1.15.2, user=, date=19700101-00:00:00)" source="mongodb_exporter.go:82"
time="2021-10-18T08:26:18Z" level=error msg="Could not get MongoDB BuildInfo: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: 11.9.1.13:27000, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp 11.9.1.13:27000: i/o timeout }, ] }!" source="connection.go:84"
time="2021-10-18T08:26:18Z" level=error msg="Problem gathering the mongo server version: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: 11.9.1.13:27000, Type: Unknown, State: Connected, Average RTT: 0, Last error: connection() : dial tcp 11.9.1.13:27000: i/o timeout }, ] }" source="mongodb_collector.go:196"
time="2021-10-18T08:26:18Z" level=info msg="Starting HTTP server for http://:9216/metrics ..." source="server.go:140"
```

I do not know if this has any relation to the problem, but this is happening on a server with no access to the internet, so I loaded the mongo-exporter image to this server using-   
On the source server with access to the internet:
` docker save -o /tmp/mongoexporter.tar bitnami/mongodb-exporter
`
On the target server:

` docker load -i mongoexporter.tar.gz
`

My mongoDB version is 4.2

Thanks,
Tamar

**Comment by denisok** [comment]
@TamarNR could you try recent image docker run -d -p 9216:9216 -p 17001:17001 percona/mongodb_exporter:0.20 --mongodb.uri=mongodb://127.0.0.1:17001
 ?

in your logs it looks like connection issue, could you check that you can connect to the mongo server ?
