### ISSUE TITLE
Is there a corresponding grafana dashboards? 

### ISSUE THREAD

**Issue by ittoyxk** [percona/mongodb_exporter#377]
Is there a corresponding grafana dashboards?

**Comment by davidmpaz** [comment]
Hi, have you check this other project in same org: https://github.com/percona/grafana-dashboards

Have fun ;-)

**Comment by ittoyxk** [comment]
Thank you.

**Comment by abhinavkulkarni** [comment]
Hi @davidmpaz,

Is there a way to bring up the dashboard in self-hosted grafana (along side self-hosted prometheus MongoDB exporter)?

That is, typically grafana dashboards have an id that you can use to pull the dashboard. I am not sure where to find such an id for the linked dashboard in your reply.

Thanks.

**Comment by davidmpaz** [comment]
Hi @abhinavkulkarni,

https://grafana.com/docs/grafana/latest/dashboards/export-import/

hope it helps

**Comment by denisok** [comment]
https://github.com/percona/grafana-dashboards
https://github.com/percona/grafana-dashboards/blob/main/misc/convert-dash-from-PMM.py the script to conver them, but something could not work.

**Comment by kristiankanchev** [comment]
I did try to use the converter(not a python expert) and I got an 
```
/Users/kristiankanchev/workspace/grafana-dashboards/venv/bin/python /Users/kristiankanchev/workspace/grafana-dashboards/misc/convert-dash-from-PMM.py
Traceback (most recent call last):
  File "/Users/kristiankanchev/workspace/grafana-dashboards/misc/convert-dash-from-PMM.py", line 176, in <module>
    main()
  File "/Users/kristiankanchev/workspace/grafana-dashboards/misc/convert-dash-from-PMM.py", line 153, in main
    with open(sys.argv[1], 'r') as dashboard_file:
IndexError: list index out of range
```
Now, I am not 100% sure which python version should I use, this was tested with 2.7. With the newer versions like 3.9, there are a few places where things need to be changed to work, but I'm not sure if it breaks the logic of the script. Can you let me know which version I should run it against?
