### ISSUE TITLE
add deb and rpm packages

### ISSUE THREAD

**Issue by denisok** [percona/mongodb_exporter#382]
**Is your feature request related to a problem? Please describe.**
DEB and RPM packages  should be build for mongodb_exporter

https://jira.percona.com/browse/PMM-5598

**Describe the solution you'd like**
GoReleaser can be wired to nfpm to generate and publish .deb, .rpm and .apk packages.
Check go-releaser NFPM section for more details: https://goreleaser.com/customization/nfpm/

**Describe alternatives you've considered**
openSUSE OBS?

**Additional context**
none

**Comment by estryzek** [comment]
I have come up with install instruction that has been tested on Ubuntu 20.04 and is working, some tweaks maybe needed for your setup. 

Hope this helps others and should be added to docs.

Assuming you are su root

# If you have many exporters running and only want one account to start the services

useradd -rs /bin/false node_exporter

# verify current package required for your build. 
wget https://github.com/percona/mongodb_exporter/releases/download/v0.20.9/mongodb_exporter-0.20.9.linux-amd64.tar.gz
tar xfv mongodb_exporter*.tar.gz
cd mongodb_exporter*.linux-amd64

mv mongodb_exporter /usr/local/bin/
chown node_exporter:node_exporter  /usr/local/bin/mongodb_exporter
cd ..
mkdir /var/run/mongodb_exporter
sudo tee /etc/systemd/system/mongodb_exporter.service<<EOF
[Unit]
Description=Mongodb_exporter
Documentation=https://github.com/percona/mongodb_exporter/
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=node_exporter
Group=node_exporter
ExecReload=/bin/kill -HUP \$MAINPID
ExecStart=/usr/local/bin/mongodb_exporter \
  --web.listen-address=0.0.0.0:9001 \
  --web.telemetry-path=/metrics \
  --mongodb.uri=mongodb://127.0.0.1:27017\
  --mongodb.collstats-colls=db1.col1,db2.col2
  --mongodb.indexstats-colls=db1.col1,db2.col2
  --mongodb.global-conn-pool

PIDFile=/run/mongodb_exporter/mongodb_exporter.pid
SyslogIdentifier=mongodb_exporter
Restart=always

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl restart mongodb_exporter.service
sudo systemctl enable mongodb_exporter.service
systemctl status mongodb_exporter.service
