### ISSUE TITLE
Collecting collstats data for collections with periods in their name

### ISSUE THREAD

**Issue by jdry1729** [percona/mongodb_exporter#383]
**Describe the bug**
I don't believe it is possible to collect coll stats data for collections which have a period in their name, e.g., `my.collection`.

**To Reproduce**
Pass the parameter `--mongodb.collstats-colls=mydatabase.my.collection` to the program.

**Expected behavior**
Periods in collection names are quite common at least from my experience. So the exporter should be able to collect data for collections which have a period in their name.

**Comment by kohtala** [comment]
I tried `--discovering-mode --mongodb.collstats-colls=db` and it also found only the top level collections without dot.

**Comment by denisok** [comment]
I guess this is about old exporter version. Doe new one works for you folks?

**Comment by kohtala** [comment]
With 0.34 adding `--collector.collstats` to previous `--discovering-mode --mongodb.collstats-colls=db` options it now collected the collections with dots.

Thank you.
