### ISSUE TITLE
Make Release errors out ::: release failed after 100.09s error=failed to build percona/mongodb_exporter:0.20: exit status 1: error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by ALakkyreddy9579** [percona/mongodb_exporter#391]
**Describe the bug**
From v0.20.9, running _make release_ failing building docker images with error 
"release failed after 100.09s error=failed to build percona/mongodb_exporter:0.20: exit status 1: error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

### I have docker up and running no issue with connecting docker(even tried with cask docker on macos)

**To Reproduce**
Failing Initially, 
run make release (version greater than v0.20.9)

**Expected behavior**
publish release(just getting started here, dont know what to expect more)

**Logs**
Please provide logs relevant to the issue
   • calculating checksums
      • checksumming              file=mongodb_exporter-feb9dc8.darwin-amd64.tar.gz
      • checksumming              file=mongodb_exporter-feb9dc8.linux-arm64.tar.gz
      • checksumming              file=mongodb_exporter-feb9dc8.darwin-arm64.tar.gz
      • checksumming              file=mongodb_exporter-feb9dc8.linux-arm.tar.gz
      • checksumming              file=mongodb_exporter-feb9dc8.linux-amd64.tar.gz
   • signing artifacts
   • docker images
      • building docker image     image=percona/mongodb_exporter:0.20
   ⨯ release failed after 100.09s error=failed to build percona/mongodb_exporter:0.20: exit status 1: error: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

make: *** [release] Error 1

**Environment**
 - OS, macOS BigSur version11.16.1
 - environment (docker, k8s, etc) docker
 - MongoDB version 

**Additional context**

**Comment by denisok** [comment]
hm, that is probably because it tries to build a container inside of a container.

could you try and pass `-v /var/run/docker.sock:/var/run/docker.sock` ?

https://github.com/percona/mongodb_exporter/blob/main/Makefile#L79

**Comment by denisok** [comment]
that is actually from the ofical doc: https://goreleaser.com/install/#running-with-docker, if it works we would need to fix it,

**Comment by denisok** [comment]
closing, feel free to re-open or comment

**Comment by felipeabezerra** [comment]
> hm, that is probably because it tries to build a container inside of a container.
> 
> could you try and pass `-v /var/run/docker.sock:/var/run/docker.sock` ?
> 
> https://github.com/percona/mongodb_exporter/blob/main/Makefile#L79

Hello everyone, I would like to say that it works for me after adding this one.
Thanks!
