### ISSUE TITLE
Useful metrics for Collection statistics 

### ISSUE THREAD

**Issue by rnovikovP** [percona/mongodb_exporter#394]
**Is your feature request related to a problem? Please describe.**

The same problem I've mentioned in  https://github.com/percona/mongodb_exporter/issues/386 (and it wasn't a problem, in reality, my misread ) we can see for metrics like  

collstats_collector:
mongodb_**testdb**_**testcol_01**_latencyStats_commands_latency{collection="testcol_01",database="testdb"} 0

top_collector:
mongodb_top_totals_**mgodatagen**_**test_10_test**_bson_6_writeLock_time

indexstats_collector:
mongodb_**testdb_testcol_01**_idx_01_accesses_ops{key_name="idx_01",namespace="testdb.testcol_01"} 0

We use the DB name and Collection name as a part of the metric. 
This is not following https://prometheus.io/docs/practices/instrumentation/#use-labels  and also complicates usage. 

**Describe the solution you'd like**
We already have labels for DB  and collection name so, I think we can remove them from the metrics name. 

**Describe alternatives you've considered**
do nothing and have hard to use metrics( 

**Additional context**

- https://prometheus.io/docs/practices/instrumentation/#use-labels

**Comment by percona-csalguero** [comment]
Implemented in https://github.com/percona/mongodb_exporter/pull/450
