### ISSUE TITLE
Error building MongoDB exporter 

### ISSUE THREAD

**Issue by vignesh-nethaji** [percona/mongodb_exporter#395]
**Mongo Db URI issue**
a. I installed all dependency packages and mongo DB also running in my machine, MongoDB port is 27017
E:\Temp\mongodb_exporter-main>go run main.go
time="2021-12-14T17:06:56+05:30" level=info msg="Starting HTTP server for http://:9216/metrics ..." source="server.go:140"
time="2021-12-14T17:06:56+05:30" level=error msg="Cannot connect to MongoDB: invalid MongoDB options: error parsing uri: must have at least 1 host"

**Comment by denisok** [comment]
@vignesh-nethaji you didn't specify uri to connect to.
