### ISSUE TITLE
How to find replication lag details using new Metrics?

### ISSUE THREAD

**Issue by ksg1998** [percona/mongodb_exporter#398]
Hi with the new naming conventions of the metrics how are we supposed to get the replication lag details?  "mongodb_mongod_replset_member_replication_lag" - This works if I give the flag --compatible-mode. But without this, suppose I want to use only the new metrics then what is the equivalent?

Also when I use --compatible-mode, only the old metrics work. Metrics such as mongodb_rs_members_state or mongodb_rs_members_configTerm return nothing.

The mongodb version I use is 4.4

**Comment by denisok** [comment]
Hi @ksg1998, sorry for the late response.

how do you run mongodb_exporter, could you please provide the keys that you are setting?

Could you just enable all the collectors with `collect-all` and then curl metrics endpoint? You will see all the metrics comming from mongo and their names.

I would try it later to test what I could see.

**Comment by peetasan** [comment]
Hi @denisok, I have the same issue as @ksg1998. I tried turning on `--collector.dbstats` I get the following extra metrics, which still doesn't include lag. Would appreciate some insight, especially that I don't see a flag `collect-all` that you mention above. Thanks

```
mongodb_dbstats_avgObjSize
mongodb_dbstats_clusterTime_signature_keyId
mongodb_dbstats_collections
mongodb_dbstats_dataSize
mongodb_dbstats_fsTotalSize
mongodb_dbstats_fsUsedSize
mongodb_dbstats_indexes
mongodb_dbstats_indexSize
mongodb_dbstats_numExtents
mongodb_dbstats_objects
mongodb_dbstats_ok
mongodb_dbstats_scaleFactor
mongodb_dbstats_storageSize
mongodb_dbstats_views

**Comment by nivimorbgp** [comment]
We're running our mongodb exporter in K8S using prometheus operator. As far as I know the underlying exporter is percona. This is the expression we use to monitor lag:

```
mongodb_mongod_replset_member_optime_date{cluster="MY_CLUSTER", state="PRIMARY"}
- 
on () group_right mongodb_mongod_replset_member_optime_date{cluster="MY_CLUSTER", state="SECONDARY"}
```
