### ISSUE TITLE
Exporter metrics suddenly disappeared

### ISSUE THREAD

**Issue by revitall** [percona/mongodb_exporter#414]
**Describe the bug**
We are using your exporter to monitor our MongoDB environments and some days ago we had an issue. Some of the metrics suddenly disappeared and we didn't make any change. The weird thing is that some environments still have all the original metrics. We tried to reinstall the exporter on the problematic environments using the one we have on the environments that work but it also didn't work. Do you have any idea why it happens? 

**To Reproduce**
1. Create a MongoDB replica set containing 3 members.
2. Install the exporter on each member.
3. Use chrome to access the exported metrics

**Expected behavior**
See all the metrics that should be there, one of them is `mongodb_mongod_wiredtiger_concurrent_transactions_availbale_tickets`

**Logs**
Couldn't find any logs if you know where there that would be great

**Environment**
 - OS: CentOS Linux 7 (Core)
 - Environment: Virtual Machine
 - MongoDB version: 4.48-enterprise

**Comment by denisok** [comment]
@revitall thanks for the report, what is the version of exporter? 
logs - by default they are redirected to the stdout/err so you should see it there, depends on how you run the exporter (systemd, container) they could be in different places (journald, docker).
It is hard to say what is going on without any error or logs, please gather the logs. It might be that connection is lost.

**Comment by revitall** [comment]
I ran the command "<path>/mongodb_exporter --version", to check which version of the exporter I'm using and that's what I got :
build date: 19700101-02:00:00
go version: go1.15.5

About the logs, I tried to check them with the command "journalctl -u mongodb_exporter.service", but there weren't any.

**Comment by denisok** [comment]
@revitall please try new version, feel free to re-open
