### ISSUE TITLE
Running the exporter

### ISSUE THREAD

**Issue by Nalum** [percona/mongodb_exporter#42]
Is it required to have one exporter per replicaset member or is having one exporter for the whole replicaset enough?

**Comment by timvaillancourt** [comment]
Hi Nalum, to get full metric coverage you will need 1 x exporter for every replica set member. We suggest you also run the 'node_exporter' project to get operating system metrics also.

Also see Percona PMM which may make this easier to setup: https://www.percona.com/software/database-tools/percona-monitoring-and-management

**Comment by Nalum** [comment]
@timvaillancourt thanks :+1:

Given that the replicaset information appears to be duplicated per member of the replicaset what's the recommended approach using those metrics?

**Comment by dbmurphy** [comment]
Typically this is to support 2 views

1) Looking at that single node and knowing how it works across everything
2) Looking at the replicaset Grafana finds all the metrics of a given name tagged with that replica set for doing a group graph such as replication lag or oplog size.

**Comment by timvaillancourt** [comment]
Yes, please see https://github.com/percona/grafana-dashboards for examples of how we use these metrics in PMM. Closing this issue, please reopen with any questions.
