### ISSUE TITLE
Mongodb Server Status is not collected

### ISSUE THREAD

**Issue by natarajanmurukan** [percona/mongodb_exporter#436]
**Mongodb_connection metrics are not being collected**
I am using version percona/mongodb-exporter 0.30.0 version and as per documentation, it is supposed to collected server status which includes mongodb_connections as metric. But unfortunately, I am not seeing any serverstatus metrics collected by the system.

**Expected behavior**
mongodb_connection metrics to be collected 

**Environment**
 - OS, - Linux
 - environment (docker, k8s, etc) - k8s
 - MongoDB version - 3.6

**Additional context**

**Comment by ShashankSinha252** [comment]
Hi @natarajanmurukan ! Thanks for reporting this issue.

I want to highlight that MongoDB server 3.6 has already hit [EOL](https://www.mongodb.com/support-policy/lifecycles). The exporter supports actively maintained versions of MongoDB only.

I would request you to try it against a newer version of MongoDB and let us know if you still face this issue.
