### ISSUE TITLE
No changelog for release v0.30.0

### ISSUE THREAD

**Issue by gokuatkai** [percona/mongodb_exporter#439]
There is no changelog entries for version v0.30.0

**Comment by denisok** [comment]
https://github.com/percona/mongodb_exporter/releases/tag/v0.30.0

there is some. But we probably need to do it in a file as well.

@gokuatkai would Release page work for you, or why Change log file better?

**Comment by gokuatkai** [comment]
I was used to check the file: `https://github.com/percona/mongodb_exporter/blob/main/CHANGELOG` - this issue is about it being out of date - maybe my title was not specific enough.

@denisok A file is usually better, but it is only my opinion, it makes search way more efficient (you can look for keyword across all versions at once), than having to go through all pages of github releases one by one.

**Comment by ShashankSinha252** [comment]
@gokuatkai , thanks for the clarification.

We missed updating `CHANGELOG` file as part of our earlier releases. It will be updated as part of our next release. We plan to create a release checklist to ensure it is not missed in future.

If you have any recommendations or suggestions, we are all ears.

**Comment by ShashankSinha252** [comment]
@gokuatkai , we have created a new release, which does have a CHANGELOG update. Please take a look at it and let us know if you have any suggestions.
