### ISSUE TITLE
Question: do I need to install a mongodb_exporter on each node?

### ISSUE THREAD

**Issue by chj9** [percona/mongodb_exporter#447]
Do I need to install a mongodb_exporter on each node? For example, if I have 3 routing nodes, 3 configuration nodes, and 3 shards, do I need to install 9 mongodb_exporters corresponding to each IP service?

Is it possible to install only one and then write multiple nodes?

**Comment by edenkr** [comment]
found an answer?

**Comment by chj9** [comment]
> Is it possible to install only one and then write multiple nodes?

no idea，currently my approach is to install a service on each server

**Comment by percona-csalguero** [comment]
Yes. The current implementation only supports connections to a single node.
