### ISSUE TITLE
TLS Connection Issue

### ISSUE THREAD

**Issue by rajavignesh** [percona/mongodb_exporter#452]
**Describe the bug**
Not able to establish a connection from exporter to MongoDB with TLS certificate.
TLS option set to "requireTLS"

**To Reproduce**
1. what parameters are being passed to `mongodb_exporter`
tls
tlsCertificateKeyFile
tlsCAFile

Full Connection String
mongodb_exporter --mongodb.uri=mongodb://mongodba:mongodba@xxx:20002/admin?tls=true&tlsCertificateKeyFile=Server.pem&tlsCAFile=ca.pem

2. describe steps to reproduce the issue
Try establishing connection using the below
mongodb_exporter --mongodb.uri=mongodb://mongodba:mongodba@xxx:20002/admin?tls=true&tlsCertificateKeyFile=Server.pem&tlsCAFile=ca.pem

**Expected behavior**
Establish connection successfully

**Logs**
ERRO[0030] Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: xxx:20002, Type: Unknown, Last error: connection() error occured during connection handshake: x509: certificate signed by unknown authority }, ] }

**Environment**
 - OS - Red Hat Enterprise Linux 8.5 (Ootpa)
 - environment (docker, k8s, etc) - VM
 - MongoDB version - 5.0.6

**Comment by ShashankSinha252** [comment]
Hi @rajavignesh , this looks like an issue with your certs. I would recommend to once try connecting with Mongo shell to figure out if issue lies with MongoDB server or MongoDB exporter.

You can also check [my comment on an earlier ticket](https://github.com/percona/mongodb_exporter/issues/430#issuecomment-1030183248). It lays out details for a toy setup to get familiar with TLS certs usage with MongoDB.

**Comment by rajavignesh** [comment]
@ShashankSinha252, able to successfully connect from Mongo shell. Facing issues when connecting with exporter. Validated the certificate and it looks good.

ERRO[0046] Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: xxx:20002, Type: Unknown, Last error: connection() error occured during connection handshake: error parsing stapled response: bad OCSP signature: crypto/rsa: verification error }, ] }
