### ISSUE TITLE
problem importing collection data from mongo db

### ISSUE THREAD

**Issue by sebusca38** [percona/mongodb_exporter#456]
**Describe the bug**
I try to get the data from my database that is in a container, however I can't find the command in prometheus to acquire it

**To Reproduce**
I use docker-compose to lift the containers
mongodb-exporter:
    image: mongodb-exporter
    container_name: mongodb-exporter
    ports:
      - 9216:9216
    expose:
      - 9216
    environment:
      - MONGODB_URI=mongodb://root:toor@mongo:27017/?authSource=admin
    networks:
      - mongodb
      - prometheus

any help or guide to start mongodb exporter correctly with docker-compose is welcome

**Comment by ShashankSinha252** [comment]
@sebusca38 , can you try connecting to MongoDB database with Mongo shell? Once we are sure that connectivity to database is not an issue, we can look into possible connectivity issue from MongoDB exporter side.

**Comment by denisok** [comment]
Hi @sebusca38 I will close this a stale. Fell free to re-open or open new one.
