### ISSUE TITLE
Restricted access to PMM-9652

### ISSUE THREAD

**Issue by weastur** [percona/mongodb_exporter#467]
There is a link to the task [PMM-9652](https://jira.percona.com/browse/PMM-9652) in the changelog for `0.31.0` version, but access seems to be restricted.

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/10865586/161506718-19b9da09-2ae3-4f1e-88bf-196d45a939ac.png">

Other tasks are available. 

P.S. It would be great if there were a chapter 'Breaking changes' in a release.

**Comment by ShashankSinha252** [comment]
@weastur, thanks for pointing it out! Let me check with my team on this.

I'll keep in mind the section about breaking changes. Would make use of it for next release.

**Comment by denisok** [comment]
yeah. We need to follow semver to avoid situation with breaking changes.
So far plan to do it after 1.0 release, but we should mention it RN right now.

We can't open issue mentioned, but it resulted in these PRs:
- https://github.com/percona/mongodb_exporter/pull/450
- https://github.com/percona/grafana-dashboards/pull/1364
