### ISSUE TITLE
v0.31.2 MongoDB Exporter - centos 7 -  does not gather any metric

### ISSUE THREAD

**Issue by gowtham500** [percona/mongodb_exporter#477]
**Describe the bug**
http://fqdn:9130/metrics --> does not show any mongodb metric. It just shows the default go lang metrics and mongodb_up gauge.

**To Reproduce**
1. system - CentOS Linux release 7.9.2009 (Core)  , mongodb version - ``4.4.13``
2. mongodb_exporter version - Version: `v0.31.2` Commit: 5ceed65
3. User Permissions
``{
    user: "username",
    pwd: "pwd",
    roles: [
        { role: "clusterMonitor", db: "admin" },
        { role: "read", db: "local" }
    ]
}``
5. Exporter is deployed as a systemd service file.
 ```
[Unit]
Description=MongoDB Exporter
After=network.target
Documentation=https://github.com/percona/mongodb_exporter
[Service]
User=mongod
Group=mongod
EnvironmentFile=/etc/mongodb_exporter/mongodb_exporter
ExecStart=/usr/local/bin/mongodb_exporter --web.listen-address=fqdn:9130
ExecReload=/bin/kill -HUP $MAINPID
ExecStop=/bin/kill -15 $MAINPID
KillMode=process

[Install]
WantedBy=default.target
```
cat /etc/mongodb_exporter/mongodb_exporter
`MONGODB_URI=mongodb://user:pwd@fqdn:27017/admin`

**Expected behavior**
``curl http://fqdn:9130/metrics`` usually shows all the metrics. Now I see only default golang metrics and mongodb_up gauge.

**Logs**
The are no connectivity errors or issues reported in systemd logs or mongod logs. The exporter is able to connect to the DB. mongodb_up gauge is visible but no other metric beyond that is produced.

**Additional context**
The issue does not seem to occur with [v0.20.9](https://github.com/percona/mongodb_exporter/releases/tag/v0.20.9)
Any release beyond that is not working

**Comment by sitoc** [comment]
I also faced the same issue when I upgrade the mongodb_exporter version from 0.20.9 to 0.31.2. The mongodb database process run but the mongodb_exporter cannot get any mongo related metrics except 'mongodb_up', could you please give a answer about that?

**Comment by ShashankSinha252** [comment]
@gowtham500 , @sitoc Thanks for reporting the issue. As part of the new release, we have implemented collect[] interface, which is similar to the one in node exporter. We will update the documentation to reflect the same.

**Comment by sitoc** [comment]
Thanks for your answer, startup the mongodb_exporter with the parameter --collect-all will resolve this issue, and can get mongo related metrics

**Comment by gowtham500** [comment]
@ShashankSinha252 as reported by @sitoc in his comment regarding parameter ``--collect-all`` - is this documented anywhere. I am unable to find info regarding this ?

**Comment by ShashankSinha252** [comment]
@sitoc Thanks for the response. I may have mixed it up with the newer collect interface modification. @gowtham500 , our documentation is out of sync with our codebase and doesn't have up to date information. I'm working on fixing it. Latest documentation PR would be up for reference in next 1-2 days.

**Comment by shdshd01** [comment]
Lost one day over this, please add --collect-all to docs.
