### ISSUE TITLE
mongo_exporter not compatible with mongo v3

### ISSUE THREAD

**Issue by nguoingoai** [percona/mongodb_exporter#485]
**Describe the bug**
May 06 12:03:49 mongo-xxx systemd[1]: Started mongo Exporter.
May 06 12:03:49 mongo-xxx mongodb_exporter[33758]: level=info ts=2022-05-06T05:03:49.227Z caller=tls_config.go:195 msg="TLS is disabled." http2=false
May 06 12:04:26 mongo-xxx mongodb_exporter[33758]: time="2022-05-06T12:04:26+07:00" level=error msg="cannot run getDiagnosticData: no such command: getDiagnosticData"
May 06 12:04:26 mongo-xxx mongodb_exporter[33758]: time="2022-05-06T12:04:26+07:00" level=error msg="cannot run getDiagnosticData: response is empty"
May 06 12:04:26 mongo-xxx mongodb_exporter[33758]: time="2022-05-06T12:04:26+07:00" level=error msg="cannot decode getDiagnosticData: <nil> for data field: unexpected data type"

**Environment**
 - OS CentOS Linux release 7.6.1810 (Core)
 - MongoDB v3.0.8

**Comment by ShashankSinha252** [comment]
@nguoingoai MongoDB exporter supports versions of MongoDB server, which have not hit EOL. You can check [EOL dates for MongoDB server](https://www.mongodb.com/support-policy/lifecycles). The server version tested by you has hit EOL, hence it is not supported.

We would recommend moving to a newer version. Let us know if you believe there is a valid use case to support older versions.

**Comment by nguoingoai** [comment]
Upgrade mongo to newer version will take me very long time , I see some other tool such as netdata still support well with EOL mongodb version , so if mongo_exporter can support this case I thinks it is very great.

**Comment by ShashankSinha252** [comment]
Can you try out the latest version of MongoDB exporter? It may work with older version of MongoDB server. You can selectively enable collectors there, so it might work for your use case.

**Comment by nguoingoai** [comment]
Yeap I am using the lasted version og mongo_exporter

**Comment by denisok** [comment]
@nguoingoai is it still fails and you have same issue?

**Comment by denisok** [comment]
@nguoingoai I will close this one, please re-open if you still see the issue
