### ISSUE TITLE
Exporter does not respect TLS certificate validation disable

### ISSUE THREAD

**Issue by ArieLevs** [percona/mongodb_exporter#489]
**Describe the bug**
exporter does not respect [tlsAllowInvalidCertificates](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.tlsAllowInvalidCertificates) and [tlsAllowInvalidHostnames](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.tlsAllowInvalidHostnames) arguments

**To Reproduce**
set the `MONGODB_URI` with a connection string to a db which has self signed certs and addressed via a custom DNS, getting error 
```
connection() error occured during connection handshake: x509: certificate is valid for [...]
```

**Expected behavior**
with real production db cluster it all works great, 
but for development env's, i have a small db with self singed certs.
i do want to use TLS, but what to skip verification process.

**Environment**
 - environment: `k8s`
 - MongoDB version: `4.4.14`

**Additional context**
Currently bypassing this issue by adding `tlsInsecure=true` to connection string
to compare, i'm able to use pythons `pymongo` client (version 3.12.0), and successfully connecting to the same mongodb

**Comment by tshcherban** [comment]
Hi @ArieLevs 
We use a [driver](https://github.com/mongodb/mongo-go-driver) that does not support mentioned flags, thus `tlsInsecure` is a good workaround for desired result. However if for some reason you really need [tlsAllowInvalidCertificates](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.tlsAllowInvalidCertificates)/[tlsAllowInvalidHostnames](https://www.mongodb.com/docs/manual/reference/connection-string/#mongodb-urioption-urioption.tlsAllowInvalidHostnames) - we can submit an issue/feature request to the driver maintainers.

**Comment by ArieLevs** [comment]
Thanks @tshcherban 
Its ok using the insecure method is also fine as its only for development, closing
