### ISSUE TITLE
mongodb_exporter crashes on startup under CentOS 6

### ISSUE THREAD

**Issue by figvam** [percona/mongodb_exporter#49]
Running mongodb_exporter from pmm-client-1.1.1-1.x86_64 RPM under CentOS 6. I added mongodb:metrics with pmm-admin first but it showed as NOT running in "pmm-admin list" output. Running mongodb_exporter manually with this command line:

`/usr/local/percona/pmm-client/mongodb_exporter -v 100 -web.listen-address=10.9.52.12:42003 -web.auth-file=/usr/local/percona/pmm-client/pmm.yml -web.ssl-cert-file=/usr/local/percona/pmm-client/server.crt -web.ssl-key-file=/usr/local/percona/pmm-client/server.key`

produces this error:

    mongodb_exporter version: 1.1.1, git commit hash: c890996b9133a3288530da4a9fb6e6fad067b55f
    HTTPS/TLS is enabled
    Listening on 10.9.52.12:42003
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6410a8]

Full error log with stack below.
[error.txt](https://github.com/percona/mongodb_exporter/files/801197/error.txt)

**Comment by thesharp** [comment]
If you just compile it and run w/o pmm-client (idk what that is), mongodb_exporter works just fine on CentOS 6.

**Comment by rnovikovP** [comment]
@figvam can you try new version?

**Comment by rnovikovP** [comment]
moved to https://jira.percona.com/browse/PMM-1241

**Comment by ShashankSinha252** [comment]
Implemented in PMM-1241
