### ISSUE TITLE
Not getting mongodb metrics

### ISSUE THREAD

**Issue by cbzchotu** [percona/mongodb_exporter#505]
cmd --./mongodb_exporter --mongodb.uri=mongodb://chandra:chandra@localhost:27017/admin?ssl=false 

getting only this much metrics.

[ec2-user@ip-10-11.24.15~]$ curl localhost:9216/metrics | grep mongo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16068    0 16068    0     0   392k      0 --:--:-- --:--:-- --:--:--  392k
# HELP mongodb_up Whether MongoDB is up.
# TYPE mongodb_up gauge
mongodb_up 1

can you help me out for this

**Comment by percona-csalguero** [comment]
You need to specify the collectors you want to enable. 
The easiest way is to specify `--collect-all` when starting the exporter.
