### ISSUE TITLE
MongoDb instance details are not rendered from exporter

### ISSUE THREAD

**Issue by chegde20121** [percona/mongodb_exporter#509]
I am currently using mongodb  exporter version 0.32.0.

I want to get the details of mongodb host os details, ip and port on which mongodb is running.

Please let me know if there is any way to get these information from mongodb exporter
cc:@shoffman-percona  @percona-csalguero  @ShashankSinha252

**Comment by BupycHuk** [comment]
Hi, I'm sure that you can do it via adding labels into scrape config.
