### ISSUE TITLE
Add metric with mongodb status

### ISSUE THREAD

**Issue by ralberto** [percona/mongodb_exporter#51]
It would be nice to have a metric indicating the mongodb status mongodb_up (0|1). There are other exporters doing that and it's really handy for monitoring. (ex. haproxy exports haproxy_up; elasticsearch_exporter exports elasticsearch_up; etc...).

**Comment by rnovikovP** [comment]
moved to https://jira.percona.com/browse/PMM-1240

**Comment by ShashankSinha252** [comment]
Implemented in [PMM-6610](https://jira.percona.com/browse/PMM-6610)
