### ISSUE TITLE
Is there any possibility to get the uri details used for configuring the exporter, or the mongodb instance details to which exporter is connected

### ISSUE THREAD

**Issue by chegde20121** [percona/mongodb_exporter#518]
Helloo,

Is there any possibility to get the uri details used for configuring the exporter, or the mongodb instance details to which exporter is connected in the metrics as metadata or labels? 

If so how can we get those ?

If not is there any way to get that?

@percona-csalguero @it-percona @it-percona-cla @asiemen-percona

**Comment by ShashankSinha252** [comment]
Hi @chegde20121 , connection URI passed to MongoDB exporter may contain sensitive information. Therefore, URI details are not exposed as part of generated metrics. There is no support to provide it in metrics.

You can always try to find the URI by checking out command line parameters used to invoke the exporter. A simple invocation of `ps` on the instance running the exporter, with output filtered using `grep` should lead to the URI passed when starting exporter.

**Comment by denisok** [comment]
any other help needed? please re-open.
