### ISSUE TITLE
Couple of beginner questions

### ISSUE THREAD

**Issue by Farfeght** [percona/mongodb_exporter#520]
First, I've tried to read all the relevant information through, but some details are still vague for me. Bear with me please.

1. Am I right asserting that this implementation doesn't enable me to access the documents inside the DB ?
1b. If so, can anyone point me to a direction where can I find helper software that can provide certain data from MongoDB to prometheus DB?

2. Am I right when I understand that I cannot configure what metrics flow from the DB?
2b. If I am wrong, which file I should edit and how?

BR.

**Comment by bluepuma77** [comment]
"This is the new MongoDB exporter implementation that handles **ALL metrics exposed by MongoDB monitoring commands**". "Enabling collstats metrics" is optional.

If you want to create custom MongoDB queries that expose custom data, maybe check something like [Prometheus MongoDB query exporter](https://github.com/raffis/mongodb-query-exporter). Grafana has a [paid tool](https://grafana.com/grafana/plugins/grafana-mongodb-datasource/) for this, see the video.

Please close the issue.

**Comment by denisok** [comment]
>Am I right when I understand that I cannot configure what metrics flow from the DB?

you can collect what collectors you enable and thus it will give you more or less metrics: https://github.com/percona/mongodb_exporter/blob/main/REFERENCE.md
