### ISSUE TITLE
server selection error: server selection timeout, current topology:  [{ Addr: 127.0.0.1:27017, Type: Unknown }, ] }"

### ISSUE THREAD

**Issue by jicki** [percona/mongodb_exporter#524]
**Version**

```
exporter version 0.32.0  and 0.33.0

```

**Logs**
Please provide logs relevant to the issue

```
time="2022-07-14T02:42:10Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: 127.0.0.1:27017, Type: Unknown }, ] }"

```

**Comment by ShashankSinha252** [comment]
@jicki , thanks for reporting the issue. It looks like a connectivity issue with the database.

I recommend you try connecting to the MongoDB server using Mongo shell and rule out connectivity issue.

**Comment by denisok** [comment]
Hi @jicki any feedback, have you you resolved the issue?

**Comment by nariman1987** [comment]
Same Issue
