### ISSUE TITLE
Failing CI Pipeline: Duplicate Metric Failure

### ISSUE THREAD

**Issue by a-gavin** [percona/mongodb_exporter#545]
**Describe the bug**
GitHub action pipelines for various PRs going back several months are failing with errors like output listed below in **Logs** when the changes they test should presumably not cause these issues, e.g. [this one](https://github.com/percona/mongodb_exporter/actions/runs/2870120705).

I have managed to trace the error down to a bug in [`makeMetrics()`](https://github.com/percona/mongodb_exporter/blob/5c3358c3bab3823588fb801a84f3eb7985d2765c/exporter/metrics.go#L241), which is called by the `ServerStatsCollectorTest` via the `ServerStatsCollector` [`collect()`](https://github.com/percona/mongodb_exporter/blob/5c3358c3bab3823588fb801a84f3eb7985d2765c/exporter/serverstatus_collector.go#L54) method.

Effectively what happens is when the collector attempts to take the MongoDB server status output and recursively unpack its Bson format in `makeMetrics()`, the multi-planner histogram data is unpacked as separate metrics with each histogram metric value having the same name causing the error. Documentation on these multi-planner histogram metrics is sparse given how recent MongoDB has implemented them, but information on it can be found in their issue tracker [here](https://jira.mongodb.org/browse/SERVER-63642) and on the commit which added this feature [here](https://github.com/mongodb/mongo/commit/43434627e89822b7e19e3a9d3aeb341be331aae6).

To fix this, these metrics should be logically grouped together and output with additional labels indicating the "bucket" of the histogram the metric corresponds to following the [Prometheus Exposition Format](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md). Once I figure out how to properly "deserialize" the Bson data passed to `makeMetrics()`, I'll submit a patch which fixes this issue.

**To Reproduce**
Rerun any existing pipelines which fail with the above error output. The ones I've seen fail are:
- 1.17.x, mongo 4.4, ubuntu latest
- 1.17.x, mongo 5.0 ubuntu latest
- 1.17.x, percona/percona-server-mongodb 4.4, ubuntu latest

**Expected behavior**
Histogram metrics should be properly generated according to the [Prometheus Exposition Format](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md) and TestServerStatusDataCollector should pass.

**Logs**
```console
=== RUN   TestServerStatusDataCollector
    serverstatus_collector_test.go:59: 
        	Error Trace:	serverstatus_collector_test.go:59
        	Error:      	Received unexpected error:
        	            	gathering metrics failed: 50 error(s) occurred:
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:1024 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:4096 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_count" { counter:<value:0 > } was collected before with the same name and label values
        	            	* collected metric "mongodb_metrics_query_multiPlanner_histograms_classicMicros_lowerBound" { untyped:<value:16384 > } was collected before with the same name and label values
```

**Comment by ShashankSinha252** [comment]
@a-gavin , thanks for highlighting the issue. This is already tracked internally in [PMM-10292](https://jira.percona.com/browse/PMM-10292). We already have a fix in place for it. We also have another [PR](https://github.com/percona/mongodb_exporter/pull/531) for histogram metrics.

I would take a look a look at your PR and see if we can derive any benefit out of it. Once again, thanks for all your effort!

**Comment by a-gavin** [comment]
Aww darn, no worries. Is the internal issue tracker the authoritative source or are both it and GH issues equivalent? CONTRIBUTING.md points at both.
