### ISSUE TITLE
[feature]split user and password from uri

### ISSUE THREAD

**Issue by naughtyGitCat** [percona/mongodb_exporter#559]
**Is your feature request related to a problem? Please describe.**
expose monitoring mongo instance URI will be helpful when handling problems, but exposing user pass is insecure

**Describe the solution you'd like**
 user and pass supply in env variables 

**Describe alternatives you've considered**
use --remark or --note to add extra info, such as --note=IP:PORT

**Comment by denisok** [comment]
similar request is in #380 . As a secure alternative so far you can use tls connection with `--web.config` which is Prometheus TLS config file

**Comment by denisok** [comment]
hm. I mixed up the things, `--web.config`  is the parameter for exporter itself. It will not help with connection to mongo. So yeah, concern is quite critical we need to address it.

**Comment by denisok** [comment]
to make it clear `--web-config` is for exporter itself, but you still use tls in a connection URI: `tls=truetlsCertificateKeyFile=Server.pem&tlsCAFile=ca.pem` in connection string instead of password.

**Comment by naughtyGitCat** [comment]
thanks, TLS may be another way to secure the exporter, and seems a little inconvenient to me. we want to expose the monitoring DB instance URL
