### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by godjil** [percona/mongodb_exporter#57]
# github.com/percona/mongodb_exporter/collector/mongos
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/asserts.go:26: assertsTotal.WithLabelValues("regular").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/asserts.go:27: assertsTotal.WithLabelValues("warning").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/asserts.go:28: assertsTotal.WithLabelValues("msg").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/asserts.go:29: assertsTotal.WithLabelValues("user").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/asserts.go:30: assertsTotal.WithLabelValues("rollovers").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/connections.go:36: connectionsMetricsCreatedTotal.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/metrics.go:60: metricsGetLastErrorWtimeTotalMilliseconds.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/metrics.go:62: metricsGetLastErrorWtimeoutsTotal.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/metrics.go:80: metricsCursorTimedOutTotal.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/network.go:32: networkBytesTotal.WithLabelValues("in_bytes").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongos/network.go:32: too many errors
# github.com/percona/mongodb_exporter/collector/mongod
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/asserts.go:26: assertsTotal.WithLabelValues("regular").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/asserts.go:27: assertsTotal.WithLabelValues("warning").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/asserts.go:28: assertsTotal.WithLabelValues("msg").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/asserts.go:29: assertsTotal.WithLabelValues("user").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/asserts.go:30: assertsTotal.WithLabelValues("rollovers").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/background_flushing.go:53: backgroundFlushingflushesTotal.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/background_flushing.go:54: backgroundFlushingtotalMilliseconds.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/connections.go:36: connectionsMetricsCreatedTotal.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/global_lock.go:79: globalLockTotal.Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/index_counters.go:35: indexCountersTotal.WithLabelValues("accesses").Set undefined (type prometheus.Counter has no field or method Set)
/usr/local/go/src/github.com/percona/mongodb_exporter/collector/mongod/index_counters.go:35: too many errors

**Comment by MathieuMailhos** [comment]
Exactly, same here: `go get github.com/percona/mongodb_exporter/collector`: `too many errors`

**Comment by godjil** [comment]
any?

**Comment by timvaillancourt** [comment]
We have fixed the build documentation and added a Makefile in #52.

In the meantime govendor is required when building.

Try the following until #52 is merged:

```
cd $GOPATH/src/github.com/percona/mongodb_exporter
govendor sync
go build -o mongodb_exporter mongodb_exporter.go
```

**Comment by AlekSi** [comment]
All dependencies are vendored now. You can install latest version with `go get -u github.com/percona/mongodb_exporter`.
