### ISSUE TITLE
how to monitoring multiple instances

### ISSUE THREAD

**Issue by yehaotong** [percona/mongodb_exporter#570]
I have multiple mongodb instance,how I use one mangodb-exporter to monitoring these mangodb?

**Comment by ShashankSinha252** [comment]
@yehaotong , at the moment, MongoDB exporter supports monitoring only via one of the following configurations:

- 1 standalone MongoDB server
- 1 replica set of MongoDB servers (multiple server along with possible arbiters)

It doesn't support targeting multiple servers in any of the above configurations. You can use multiple instance of MongoDB exporter to monitor multiple targets. The simplicity of creating a new MongoDB exporter process helps us avoid complexity of supporting multiple MongoDB instance using a single exporter instance.

**Comment by adnull** [comment]
You can use my implementation of multi-target support: https://github.com/adnull/mongodb_exporter_mt
I will keep this code up to date with main as long as possible.
