### ISSUE TITLE
License Inconsistency in code files

### ISSUE THREAD

**Issue by chattarajoy** [percona/mongodb_exporter#578]
The license applied to the repository is Apache2.0 as mentioned on the top level. Still, there are a lot of files under the exporter/ directory that have a license header saying they are AGPL licenses. 

Is this intentional or is that a miss when updating the license header of all the files? If that is a miss I would be happy to get create PR for updating the license.

**Comment by luisgerhorst** [comment]
The dependency used at https://github.com/percona/mongodb_exporter/blob/301981277b526948778f9ff7aea7c0682c2402a7/exporter/topology_info.go#LL24C31-L24C31 is under GPLv2 (https://github.com/percona/percona-toolkit/blob/3.x/COPYING), if I understand it correctly changing the file's license will either require the dependency to be dropped or the dependency's license to be changed.

**Comment by chattarajoy** [comment]
Oh there's a lot of difference between Apache and LGPL licenses in terms of commercial use.

**Comment by rnovikovP** [comment]
@marctc, you were right to point out the error in the copy-paste process. AGPL was mistakenly added. Regarding the Toolkit files, we are currently working on a solution. We want you to know that we aim to ensure this project meets the appropriate Apache 2.0 license.

**Comment by bboreham** [comment]
Trying to clear up one confusion: the referenced text "doesn't make too much of a difference from the legal standpoint" is about `(C) 2017` versus `(C) 2022`.  Nothing to do with the licence text.

**Comment by BupycHuk** [comment]
We've removed percona-toolkit from dependencies and cleaned up headers in all files, so the repository should meet Apache 2.0 license.
