### ISSUE TITLE
Missing (probably) labels from mongos

### ISSUE THREAD

**Issue by thesharp** [percona/mongodb_exporter#59]
I've added my mongos hosts to Prometheus and here's the sample of the labels I see from there:

```
mongodb_mongos_connections{alias="fqdn",instance="fqdn:9104",job="mongodb",state="current"}
```

Isn't there supposed to be a `cluster` label for "MongoDB Cluster Summary" dashboard to work correctly? Or should I just add it during the scrape step?

**Comment by timvaillancourt** [comment]
Yes, 'cluster' is used for many dashboards. In PMM '--cluster <name>' during 'pmm-admin add mongodb:metrics' will add all required labels to metrics gathered by PMM's Prometheus.

To do it yourself I would add it during the scrape step as you mention.
