### ISSUE TITLE
Compiled assets for release 2.32.0

### ISSUE THREAD

**Issue by gongomgra** [percona/mongodb_exporter#594]
Hello team,

I see you provided compiled assets for previous versions `v0.33.0`, ` v0.34.0`, and `v0.35.0`. Do you plan to provide them for the latest released version `v2.32.0`? 

**Describe the solution you'd like**
Compiled binaries are available for the latest version in the same way they are for previous ones.

**Describe alternatives you've considered**
In case it is not officially provided, we would have to compile it on our side.

**Additional context**
None.

**Comment by fmulero** [comment]
Hi,

I've just seen version `v0.36.0` was [recently released](https://github.com/percona/mongodb_exporter/releases/tag/v0.36.0). Has [tag v2.32.0](https://github.com/percona/mongodb_exporter/tree/v2.32.0) been created by mistake?  Maybe @atymchuk could help us to solve the doubt.

**Comment by rnovikovP** [comment]
Greetings everyone! 👋 
@fmulero is correct, as well as an assumption in https://github.com/percona/mongodb_exporter/issues/613#issue-1527674133.  
I'd like to talk about the recent confusion regarding our exporter's version update. 

The release of v2.X was an unintentional technical error. 🐛  
We plan to stick with the current 0.X version for now. We are currently working on updating dependencies ⚒️ , retagging released versions, and preparing to release a new version within the 0.X stream 🚀 . 

We'd like to apologize for any inconvenience caused. 🙇

**Comment by rnovikovP** [comment]
Greetings everyone! 
We have successfully resolved the v2.X issues and have re-tagged the data with https://github.com/percona/mongodb_exporter/releases/tag/v0.38.0. All standard assets are now accessible with this latest release. 
We apologize for any inconvenience caused.
