### ISSUE TITLE
Mongodb_exporter can't start normally

### ISSUE THREAD

**Issue by weily2** [percona/mongodb_exporter#596]
Mongodb_exporter can't start normally，the logs bellow:
Nov 20 22:35:49 perf_db2 signalfx-agent: time="2022-11-20T22:35:49-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:35:59 perf_db2 signalfx-agent: time="2022-11-20T22:35:59-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:36:09 perf_db2 signalfx-agent: time="2022-11-20T22:36:09-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:36:19 perf_db2 signalfx-agent: time="2022-11-20T22:36:19-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:36:29 perf_db2 signalfx-agent: time="2022-11-20T22:36:29-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:36:39 perf_db2 signalfx-agent: time="2022-11-20T22:36:39-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:36:49 perf_db2 signalfx-agent: time="2022-11-20T22:36:49-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:36:59 perf_db2 signalfx-agent: time="2022-11-20T22:36:59-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 277 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:37:09 perf_db2 signalfx-agent: time="2022-11-20T22:37:09-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:37:19 perf_db2 signalfx-agent: time="2022-11-20T22:37:19-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:37:29 perf_db2 signalfx-agent: time="2022-11-20T22:37:29-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:37:39 perf_db2 signalfx-agent: time="2022-11-20T22:37:39-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519
Nov 20 22:37:49 perf_db2 signalfx-agent: time="2022-11-20T22:37:49-05:00" level=error msg="Could not handle message from Python" error="parse error: expected number near offset 278 of 'values'" monitorID=1 monitorType=collectd/mongodb runnerPID=1519

and when i visit the url  in my browser,it come across the 404 page
![image](https://user-images.githubusercontent.com/31880042/202960792-7aea868b-5747-4f4a-af8f-ead16bab30bc.png)

and my mongodb_exporter.service is :
![image](https://user-images.githubusercontent.com/31880042/202961012-f0ba211c-31f2-44b0-a85f-929301d8db4e.png)

can anybody help solve this problem?

**Comment by liuhe-trec** [comment]
The same issue as yours😭
