### ISSUE TITLE
Expose per-database metrics

### ISSUE THREAD

**Issue by jperville** [percona/mongodb_exporter#60]
Could it be possible to backport https://github.com/dcu/mongodb_exporter/pull/32 from the upstream fork to this project? We would like to expose the dbStats (number of objects, indexes etc) to prometheus.

**Comment by rnovikovP** [comment]
moved to https://jira.percona.com/browse/PMM-1239

**Comment by djoul2706** [comment]
Hi, 
is it available or not ? 
I can't found any db level metrics exposed with the following command : 

/tmp/mongodb_exporter-0.20.5.linux-amd64/mongodb_exporter \
  --discovering-mode --compatible-mode \
  --mongodb.collstats-colls=db1.col1,db2.col2

what did i miss ? 

regards,
Julien

**Comment by khuongduybui** [comment]
It is _not_ available, the JIRA issues has been on hold for years. We might as well make my own fork at this point...

**Comment by iamanv** [comment]
@rnovikovP Aren't we exposing a few DB metrics for shards here https://github.com/percona/mongodb_exporter/blob/75adba41a2d8e9c4d5f5496bd2a509eadc0dd462/exporter/v1_compatibility.go#L1300 ? Unless I am missing something, we are making use of the same thing as the upstream repo to create metrics.

**Comment by khuongduybui** [comment]
I enabled `--compatible-mode` but still did not see `mongodb_mongos_db_indexes_total`.
I want to give my mongodb instance enough memory to store entire indices in memory so this metric is important to me.
