### ISSUE TITLE
Arbiter uptime absent

### ISSUE THREAD

**Issue by superset1** [percona/mongodb_exporter#629]
Hello
In version 0.37.0, the MongoDB arbiter does not have `mongodb_instance_uptime_seconds` metrics or other similar metrics *uptime*
I have to install the old version 0.11.2 for arbiter

**To Reproduce**
1. download release 0.37.0
2. configure systemd unit
```
[Unit]
Description=Prometheus exporter for MongoDB (https://github.com/percona/mongodb_exporter)
After=network.target mongod.service

[Service]
Type=simple
RestartSec=5s
Restart=on-failure
User=mongodb-exporter
Group=mongodb-exporter
ExecStart=/usr/local/bin/mongodb-exporter --discovering-mode --mongodb.direct-connect --mongodb.uri=mongodb://mongodbexporter:mongodbexporter@127.0.0.1:27017/admin
ExecStop=/bin/kill -s SIGINT $MAINPID

[Install]
WantedBy=multi-user.target
``` 

Also I tried
--compatible-mode
--collector.diagnosticdata
--collector.collstats

**Expected behavior**
I expect that metrics *uptime* will be available.

**Environment**
 - debian 10,
 - MongoDB version
   - 4.4.18
   - 6.0.4

**Comment by rnovikovP** [comment]
Thank you for the report! We appreciate your feedback. The issue you reported will be resolved with the upcoming release of the exporter. You can find more information about the fix at https://github.com/percona/mongodb_exporter/pull/655. Thank you for your patience while we work on this.
