### ISSUE TITLE
Provide official docker image on docker hub

### ISSUE THREAD

**Issue by heartwilltell** [percona/mongodb_exporter#64]
It would be really userful

**Comment by Exordian** [comment]
+1 enabling an automated build on dockerhub should just take a few minutes

**Comment by rnovikovP** [comment]
We have  similar requests for all  exporters so you can  follow https://jira.percona.com/browse/PMM-1026 to track progress

**Comment by TheQueenIsDead** [comment]
Super old issue, but if anyone is looking for an image, [Bitnami](https://bitnami.com/) has one available

GitHub: https://github.com/bitnami/bitnami-docker-mongodb-exporter
Docker Hub: https://hub.docker.com/r/bitnami/mongodb-exporter/

Could be worth linking to it in the README, though most avid Googlers will likely find it

**Comment by AsterYujano** [comment]
Hello, I was looking for a docker image recently (to provide Grafana insights of a MongoDB sharding) and indeed it would be nice to have it in the Readme, I am going to add it.

**Comment by denisok** [comment]
percona/mongodb_exporter:0.20

**Comment by nick4fake** [comment]
Is there any guide? Looks like there is no instruction on Docker Hub

**Comment by denisok** [comment]
@nick4fake standard README have some instructions: https://github.com/percona/mongodb_exporter#docker
