### ISSUE TITLE
 no dashboard?

### ISSUE THREAD

**Issue by z3473** [percona/mongodb_exporter#642]
How to use grafana to show it, no dashboard?

**Comment by BupycHuk** [comment]
Hi, we have grafana dashboards in this repository https://github.com/percona/grafana-dashboards

**Comment by grenade** [comment]
for what it's worth, you can make use of the dashboards like so:
```shell
repo_path=${HOME}/git/percona/grafana-dashboards
git clone https://github.com/percona/grafana-dashboards.git ${repo_path}
for dashboard in ${repo_path}/dashboards/MongoDB/*.json; do
  python2 ${repo_path}/misc/convert-dash-from-PMM.py ${dashboard}
done
```
then just manually import each dashboard from `${repo_path}/dashboards/MongoDB/*.json` using your grafana dashboard importer.

**Comment by yod527** [comment]
I've also found this dashboard working great with Percona exporter [https://grafana.com/grafana/dashboards/16490-opstree-mongodb-dashboard/](https://grafana.com/grafana/dashboards/16490-opstree-mongodb-dashboard/)
