### ISSUE TITLE
Release Arch Binaries

### ISSUE THREAD

**Issue by Smuggla** [percona/mongodb_exporter#65]
With Go's vendoring being as awesome as it is, could you please release compiled arch versions of the exporter.

This is the main reason I am not using this exporter personally.

Thanks!

**Comment by AlekSi** [comment]
We are going to release static binaries soon. In the meantime, you can `go get` exporter – dependencies are now vendored.

**Comment by AlekSi** [comment]
Please test the latest released binary.

**Comment by rnovikovP** [comment]
We have similar requests for all exporters so you can follow https://jira.percona.com/browse/PMM-1026 to track progress

**Comment by ShashankSinha252** [comment]
Implemented for MongoDB exporter
