### ISSUE TITLE
Missing oplog metrics in new version of exporter

### ISSUE THREAD

**Issue by gowtham500** [percona/mongodb_exporter#658]
Old Version of Exporter has below metrics

```
# HELP mongodb_mongod_replset_oplog_head_timestamp The timestamp of the newest change in the oplog
# TYPE mongodb_mongod_replset_oplog_head_timestamp gauge
mongodb_mongod_replset_oplog_head_timestamp 1.683804454e+09
# HELP mongodb_mongod_replset_oplog_tail_timestamp The timestamp of the oldest change in the oplog
# TYPE mongodb_mongod_replset_oplog_tail_timestamp gauge
mongodb_mongod_replset_oplog_tail_timestamp 1.662424292e+09
```

I am using the new version - `mongodb_exporter-2.37.0.linux-amd64`
Can you please share corresponding metrics in new version of the exporter which captures oplog head timestamp and tail timestamp. I am unable to find them.

**Comment by horihel** [comment]
google brought me here, so i might as well help out with a suggestion

maybe `mongodb_ss_oplog_latestOptime` and `mongodb_ss_oplog_earliestOptime` are the right replacements.
