### ISSUE TITLE
Multi-Target Support

### ISSUE THREAD

**Issue by jicki** [percona/mongodb_exporter#659]
**Describe the solution you'd like**
Exporter supports the multi-target pattern. This allows running a single instance of this exporter for multiple mongo  targets. 

https://prometheus.io/docs/guides/multi-target-exporter/

**Comment by adnull** [comment]
I've implemeted this in https://github.com/percona/mongodb_exporter/pull/653 but still waiting approval.
You can get it from my https://github.com/adnull/mongodb_exporter_mt or as a docker image  https://hub.docker.com/r/adnull/mongodb_exporter

**Comment by kubeop** [comment]
> I've implemeted this in #653 but still waiting approval. You can get it from my https://github.com/adnull/mongodb_exporter_mt or as a docker image https://hub.docker.com/r/adnull/mongodb_exporter

It would be even better if the username and password were placed in the exporter parameter instead of targets

**Comment by adnull** [comment]
Hi! Sure, you must specify username and password as parameters for the exporter, like that:
`--mongodb.uri=mongodb://user1:pass1@127.0.0.1:27017/admin,mongodb://user2:pass2@127.0.0.1:27018/admin`
but you don't have to specify full uri in the target parameter when you are querying data, just host:port, like that:
`?target=mongodb://127.0.0.1:27017`
or
`?target=mongodb://127.0.0.1:27018` for the second host

**Comment by davidvesp** [comment]
Any update? I have check the https://github.com/percona/mongodb_exporter/pull/653 but still waiting approval.

**Comment by gthieleb** [comment]
As MT support is in upstream is this ticket still relevant?

**Comment by hayk96** [comment]
Hello everyone,

thank you for this feature. However, it seems that for multiple target support, we must specify multiple MongoDB targets via the `--mongodb.uri=` flag and then call the target that we want to scrape using the `/scrape` endpoint. 
At first glance, this feature appears similar to the support that Redis Exporter provides ([link](https://github.com/oliver006/redis_exporter?tab=readme-ov-file#kubernetes-sd-configurations)), but it isn't. It's a bit confusing and does not fully adhere to the points defined in [this](https://prometheus.io/docs/guides/multi-target-exporter/#the-multi-target-exporter-pattern) Prometheus documentation.

**Comment by adnull** [comment]
@hayk96 Hi. Could you elaborate what do you find incompatible with prometheus multi-target pattern? The feature works exactly as you've written - specify multiple targets and call /scrape with target query parameter to get target's metrics.

**Comment by adnull** [comment]
Got it. Thanks. 
It isn't impossible, but on first glance opens security vulnerabilities like passing access credentials via GET request or possible DDos attacks using someone's open exporter without a firewall. It is just my opinion, but if you don't know a final list of servers it could be a design issue.. 
Anyway you could propose this behavior in a new request to open discussion.

**Comment by hayk96** [comment]
I’m not in favor of passing credentials via a GET request; I agree with you that it’s not correct. 
OK, we need to discuss this in another issue. Thank you for your thoughts and response @adnull!
