### ISSUE TITLE
roadmap of percona/mongodb_exporter and dcu/mongodb_exporter

### ISSUE THREAD

**Issue by zhihuiFan** [percona/mongodb_exporter#66]
I'm new to open source community,  but looks too many branches makes user and contributor hard to choose. 

Take mongodb_exporter for example,  I know/use dcu/mongodb_exporter first and then I would like to contribute to it during use.  but then I found percona/mongodb_exporter has more features I want already.  like `MongoDB WiredTiger storage-engine metrics`.   I'm thinking if  I should turn to use percona/mongodb_exporter.

since percona/mongodb_exporter is forked from dcu/mongodb_exporter,   So my greenhand question is why not  percona/mongodb_exporter contribute back to dcu,  if so,  all the users will easy to choose.  No offence,  I just want to know more about open source community.

**Comment by dbmurphy** [comment]
The short answer is we needed more control and could not wait months for pull requests, but there are differences on features we wanted that others didn't. As this fork is what PMM uses I would not want to block such a big project on waiting months for PR merging (has happened)

**Comment by zhihuiFan** [comment]
I see.  Thank you for your answering!   

is it welcomed that if I find some nice feature here and want to send pull request to dcu?  What policy shall I follow, like if I want to copy some code,  shall I add some comments like "// the following code is copied from percona/mongodb_exporter"  and // copy from percona/mongodb_exporter ended".   Looks this way will make the code pretty dirty but I also think  copy silently is not polite.   shall I represent the fact in commit message?

**Comment by dbmurphy** [comment]
We some times send PR up, but you might just raise an issue and ask, my team does not manage this anymore and do not want to speak for Percona engineering.
>

**Comment by rnovikovP** [comment]
@zhihuiFan we are planning to have more regular checks on new features in dcu and have dedicated people to review PR into our repo. So fill free to send us PR you needed.

**Comment by zhihuiFan** [comment]
I see,  thank you all!
