### ISSUE TITLE
Mongodb monitoring in windows

### ISSUE THREAD

**Issue by hy-whs** [percona/mongodb_exporter#667]
We have a few Windows servers running MongoDB on them and i am currently looking to start monitoring them using Prometheus. Looking online I couldn't find any build or relevant documentation regarding a Windows deployment. I searched the issues in the repo but still nothing came up.

**Comment by atymchuk** [comment]
@hy-whs We are not currently building this exporter for all flavors of operating systems, but if you are looking to be able to run `mongodb_exporter` on Windows, you can do so as follows:
1. clone this repository
2. checkout a specific tag,  for example: `git checkout v0.38.0`
3. running `GOOS=windows GOARCH=amd64 goreleaser build --clean --single-target`

This should get you a binary in the `build` directory.
