### ISSUE TITLE
mongos metrics in compatible mode

### ISSUE THREAD

**Issue by 4orty** [percona/mongodb_exporter#676]
According to the source code, three types of metrics are added in compatible mode. (specialMetrics, cacheEvitedTotalMetric, mongosMetrics)
I don't have these metrics when I'm not in compatible mode, is there a metric that can replace this metric?

For example, `mongodb_mongos_sharding_chunks_total` metric is not in compatible mode, but it is still used in grafana dashboard(https://github.com/percona/grafana-dashboards/blob/main/dashboards/MongoDB/MongoDB_Cluster_Summary.json). I want to replace `mongodb_mongos_sharding_chunks_total` with something else in not compatible mode but i can't find. Is there a possible way?

```
if d.compatibleMode {
		metrics = append(metrics, specialMetrics(d.ctx, client, m, logger)...)

		if cem, err := cacheEvictedTotalMetric(m); err == nil {
			metrics = append(metrics, cem)
		}

		nodeType, err := getNodeType(d.ctx, client)
		if err != nil {
			logger.WithFields(logrus.Fields{
				"component": "diagnosticDataCollector",
			}).Errorf("Cannot get node type to check if this is a mongos: %s", err)
		} else if nodeType == typeMongos {
			metrics = append(metrics, mongosMetrics(d.ctx, client, logger)...)
		}
	}
```

**Comment by igroene** [comment]
the mongodb_mongos_sharding_chunks_total is only available when scraping metrics from a mongos router. Make sure you are running exporter against a mongos instance
