### ISSUE TITLE
mongodb_exporter can’t collect mongos connections：mongodb_mongos_connections

### ISSUE THREAD

**Issue by carry2017123** [percona/mongodb_exporter#678]
**Describe the bug**
mongodb_exporter can’t collect mongos connections：mongodb_mongos_connections
**To Reproduce**
./mongodb_exporter --mongodb.uri=mongodb://127.0.0.1:27017/admin --discovering-mode --compatible-mode --collector.indexstats --collector.replicasetstatus --collector.diagnosticdata --collector.dbstats --collector.topmetrics --collector.collstats 

**Expected behavior**
get mongodb_mongos_connections result

**Logs**
no error log

**Environment**
 - OS,
 ubuntu
 - environment (docker, k8s, etc)
 k8s
 - MongoDB version
 -mongodb 4.4.19

**Additional context**

**Comment by igroene** [comment]
looks like that metric is no longer available. Try looking for `mongodb_connections` instead
