### ISSUE TITLE
Separate linters from go.yml to another job.

### ISSUE THREAD

**Issue by JiriCtvrtka** [percona/mongodb_exporter#701]
Problem: 
Right now some PRs failing on linters. We run them unnecessarily many times due to the matrix configured for different MongoDB versions.

Solution: 
We want to extract "Run checks/linters" to a new separate go.yml job, which will allow the linters to only run once.

**Comment by anishrajan25** [comment]
@JiriCtvrtka  I would like to pick this up!

**Comment by JiriCtvrtka** [comment]
@anishrajan25 Cool. Thanks for you interest and feel free to take it.

**Comment by anishrajan25** [comment]
@JiriCtvrtka I checked the workflow file, and I can se currently  the "Run checks/linters" step will be triggered by pushes to the "main" and "release-0.1x" branches, tag pushes that match the specified pattern, and pull request events.

The requirement now is to run it only when there any changes to a PR, right?

**Comment by JiriCtvrtka** [comment]
@anishrajan25 We run this job 6x for every image
https://github.com/percona/mongodb_exporter/blob/main/.github/workflows/go.yml#L23-L28

In case of lint its enough to run it only with one image. Please seperate linters to a new job and include only once image there. You can also run it only where there are changes. As you said before. Thank you.

**Comment by anishrajan25** [comment]
@JiriCtvrtka I have raise #702 to solve this.
