### ISSUE TITLE
How to monitor multiple mongodb databases in one mongodb_exporter

### ISSUE THREAD

**Issue by Wangyxiang** [percona/mongodb_exporter#703]
Whether to support configuring multiple mongodb information in one mongodb_exporter and distinguish it in proemtheus

**Comment by tregubov-av** [comment]
As far as I know there is no such option at the moment.
Related query:
issues: https://github.com/percona/mongodb_exporter/issues/659

**Comment by adnull** [comment]
the code implementing this feature is still waiting for an approval, meantime you can use adnull/mongodb_exporter prebuilt docker image with this feature or checkout the code from https://github.com/adnull/mongodb_exporter_mt

**Comment by BupycHuk** [comment]
The PR from @adnull was merged, so I'm closing this task
