### ISSUE TITLE
Collector for working with data from the system profile

### ISSUE THREAD

**Issue by tregubov-av** [percona/mongodb_exporter#707]
There is often a need to monitor requests entering the system profiler.
As a rule, slow queries specified by the user go there.
We really need functionality that can monitor at least their quantity.

I would like to receive a metric that outputs data from a `db.system.profile.find().count()` query
In the future, the functionality can be expanded and some useful aggregations can be obtained from system profile

There is a similar implementation in this exporter, but unfortunately it has not been supported for a long time
https://github.com/dcu/mongodb_exporter/blob/master/collector/profile_status.go

**Comment by mikle7771** [comment]
I implemented the slow query functionality in this PR https://github.com/percona/mongodb_exporter/pull/710

**Comment by tregubov-av** [comment]
Thank you!
