### ISSUE TITLE
Cannot connect to server using url mongodb://****:****@127.0.0.1:27017: no reachable servers  source="connection.go:86"

### ISSUE THREAD

**Issue by bmurrellbc** [percona/mongodb_exporter#717]
**Describe the bug**
I can't connect mongo_exporter to the database. I've created a username that I can connect via Compass with when using the same URI.

**Environment**
 - RHEL 8.7
 - 2 node replicaset, testing on primary
 - MongoDB version - 6.0.10

**Comment by bmurrellbc** [comment]
Looks like an old version was installed. Now working.

**Comment by mgourlay64** [comment]
Hi,

I am encountering this issue on the new release v0.40.0

`Cannot connect to server using url mongodb://****:****@localhost:27017: no reachable servers  source="connection.go:86"`

I have created a user with the rights needed, I can connect with compass with the same URI, but here it is not working, any idea ?
