### ISSUE TITLE
Build release command failed

### ISSUE THREAD

**Issue by NSi1974** [percona/mongodb_exporter#718]
Hi all !

I've got a problem building the release as decribed in the README.
After launching the "make release" command, it failed with this error :

docker run --rm --privileged \
        -v /home/ec2-user/mongodb_exporter:/go/src/github.com/user/repo \
        -w /go/src/github.com/user/repo \
        goreleaser/goreleaser release --snapshot --skip-publish --rm-dist
Flag --rm-dist has been deprecated, please use --clean instead
  • starting release...
  ⨯ release failed after 0s                          error=yaml: unmarshal errors:
  line 91: field replacements not found in type config.NFPM
make: *** [release] Error 1

Not sure what I can do to prevent this error.

Thank you for the suggestion you could provide !

**Comment by FENG-MASTER** [comment]
I have encountered the same situation and I would like to seek help as well.

**Comment by NSi1974** [comment]
Glad to see that I'm not the only one !

**Comment by npabllla** [comment]
I also have the same error, perhaps there is already a solution?

**Comment by NSi1974** [comment]
To my knowledge, no solution available for now sadly.

**Comment by npabllla** [comment]
I set goreleaser/goreleaser:v1.18.2 [here](https://github.com/percona/mongodb_exporter/blob/main/Makefile#L80) instead of latest version and it worked for me

**Comment by NSi1974** [comment]
I confirm : it's all good now !!! Thank you for the tip @npabllla
