### ISSUE TITLE
How to calculate replication Lag.

### ISSUE THREAD

**Issue by ashoksahoo** [percona/mongodb_exporter#73]
The readme has replication lag, but I guess it is supposed to be calculated from two different metrics by joining them. What is the correct way to do that?

**Comment by rnovikovP** [comment]
You probably asking about  this  - https://github.com/percona/grafana-dashboards/blob/master/dashboards/MongoDB_Cluster_Summary.json#L1449  

The dashboard to use this metrics

**Comment by paragor** [comment]
but it show only maximum lag, and not lag per member

**Comment by igroene** [comment]
lag by member is now possible since https://github.com/percona/mongodb_exporter/pull/804
