### ISSUE TITLE
Mongo-exporter compatibility

### ISSUE THREAD

**Issue by arsbest** [percona/mongodb_exporter#744]
### Discussed in https://github.com/percona/mongodb_exporter/discussions/742

<div type='discussions-op-text'>

<sup>Originally posted by **arsbest** November  3, 2023</sup>
Hi! 
I would like to know which versions of mongo the mongo exporter is compatible with.
Possible compatibility issue or incorrect configuration?

I am currently using the following versions:
- Mongo 4.0 instance
- percona/mongodb_exporter:0.34.0

I connect from a user with write and read permissions.

Container launch options:
```
- args:                        
  - --web.listen-address=:9216 
  - --collect-all              
  - --no-mongodb.direct-connect
  - --log.level=error          
  - --compatible-mode          
  - --discovering-mode
```

The logs contain the following errors:
```
time="2023-11-03T10:35:01Z" level=error msg="cannot get $indexStats cursor for collection MY_COLLECTION: connection(MY_IP:8635[-96]) failed to write: context canceled"  

time="2023-11-03T10:35:01Z" level=error msg="Failed to get $dbstats for database MY_DB: connection(MY_IP:8635[-97]) failed to write: context canceled" 

time="2023-11-03T10:35:01Z" level=error msg="cannot get $indexStats cursor for collection MY_COLLECTION: (Unauthorized) not authorized on MY_DB to execute command {
 aggregate: \"system.profile\", pipeline: [ { $indexStats: {} } ], cursor: {}, lsid: { id: UUID(\"\") }, $clusterTime: { clusterTime: Timestamp(1699007701, 1636)
, signature: { hash: , keyId: 8 } }, $db: \"MY_DB\" }" 
```</div>

**Comment by BupycHuk** [comment]
Hello, the minimum version supported is 4.4 now

**Comment by arsbest** [comment]
> Hello, the minimum version supported is 4.4 now

Thank you for your answer.
Where can I find a list of all dependencies?
Then how can I monitor Mongo 4.0?

**Comment by avishefi** [comment]
> Hello, the minimum version supported is 4.4 now

@BupycHuk Why? The Go Mongo driver compatibility is stated for >= 3.6: https://www.mongodb.com/docs/drivers/go/current/compatibility/#compatibility-table-legend

https://github.com/percona/mongodb_exporter/blob/v0.40.0/go.mod#L17

**Comment by BupycHuk** [comment]
@avishefi because it's EOL, it's not only about driver compatibility, but queries and etc. So we decided to not spend our time on trying to support versions that already EOLed.
