### ISSUE TITLE
Can't get metric if first host is not available (others are)

### ISSUE THREAD

**Issue by elafontaine** [percona/mongodb_exporter#749]
**Describe the bug**

We use the same configuration of URI for different server's type, so we have a Mongo connection URI string that refer to something akin to `mongodb://<REDACTED>:27018,<REDACTED>:27019/admin`.  The important thing to understand is that on one type of server, the port 27018 will exist, while on the other, the port 27019 will exist.  The bug seems to be that only the first host is checked to establish the connection initially, causing the exporter to not expose the metric (see other bug about lost of connectivity which I guess is related).  I know that wasn't case until yesterday when bitnami updated their latest version of the container (we use the bitnami container).  The behaviour before yesterday was that the nodes I had with the 27019 were reported even though they didn't have anything on port 27018.  Same for the node that had the port 27018 and nothing on their port 27019.  Now, since the update, I lost the metrics of my nodes with port 27019, but didn't lose those with port 27018.

We tried a couple things ;
- Re-order the host list
- Remove the unnecessary host on one server
but everything points to a bug where the first host being unreachable stop any metric reporting of the other hosts.

-------
Node with Port 27019 behaviour; 
When we start the bitnami container, we get the following log on repeat for the container that have the port 27019 ; 
```
time="2023-11-22T13:23:05Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: <REDACTED>:27018, Type: Unknown, Last error: dial tcp <REDACTED>:27018: connect: connection refused }, ] }"
```
The exporter is then reporting nothing and we aren't receiving any data.

-------
Node with Port 27018 behaviour:
When we start the bitnami container, we get the following log ONCE; 
```
time="2023-11-22T12:15:54Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Unknown, Servers: [{ Addr: <REDACTED>:27019, Type: Unknown, Last error: dial tcp <REDACTED>:27019: connect: connection refused }, ] }"
```
The exporter is reporting the metric he observe from the port 27018.

--------
I believe the bug is due to the mongo driver, 
https://github.com/percona/mongodb_exporter/blob/main/exporter/exporter.go#L31   < import
https://github.com/percona/mongodb_exporter/blob/main/exporter/exporter.go#L376 < connect (?)
but I'm not a specialist so I wanted some confirmation before moving on.

**To Reproduce**
Steps to reproduce the behaviour:
1. what parameters are being passed to `mongodb_exporter`
    A mongo URI with multiple hosts, first one being unreachable
2. describe steps to reproduce the issue
    Start the exporter and observe the failure to expose the second host metrics

**Expected behaviour**
    I would expect the metric observed through the second host to be reported

**Logs**
Please provide logs relevant to the issue
(see above)

**Environment**
 - OS,   bitnami (flatcar underneath)
 - environment (docker, k8s, etc).  docker
 - MongoDB version. 4.4

**Additional context**
(see above)

**Comment by elafontaine** [comment]
We changed our mongodb-exporter to use 0.39.0 in the mean time.

**Comment by pflong** [comment]
@elafontaine  May be you can try to start an exporter on each port instead of using `multi target`, it would be much simpler.

you can see my issue, https://github.com/percona/mongodb_exporter/issues/761

**Comment by gthieleb** [comment]
Sorry for this naive question. I would like to connect the exporter to all instances of a replica set by using a mongodb connection string with multiple ip addresses in url. In my oppinion this is something which should also work in versions <0.40 (multi target support). Is this supported by the exporter?

**Comment by elafontaine** [comment]
@pflong the way our IaC is done, we would like to avoid adding many variables as much as possible.  This multi-target thing was working fine previously and did what we expected it to do.  The fact that it's stopping after only the first one that failed is worrisome to me as I'm wondering how the failure scenario is being handled.  

This **feels** like a golang standard thing that I'm not aware...  Maybe you could point me in the right direction in regards to this as I've seen another library that started to fail in the same way as mongo-exporter.

I reported the issue so that other people could see it and maybe discuss a resolution.  For now, we prefered to leave it to 0.39 until there is a resolution (if it ever comes...).   However, we would prefer to leave this to "latest" as to get updates, but that would require changes in our IaC that we aren't ready to look into yet.

**Comment by elafontaine** [comment]
@gthieleb , I believe you may want to look at the documentation as they support mongo connection URI.  What we use is "multi-target" and that means that we target 2 endpoints on a local machine.  One will exist, the other will not.  

For a mongo connection URI, this issue means that if the first host in the mongo connection URI list isn't available for some reason, the exporter will just fail to connect to the 2nd and 3rd instance.

**Comment by elafontaine** [comment]
Could I get somebody else to corroborate what I said ? I want to ensure this is not just a "me" problem because of some settings somewhere that I've missed.

**Comment by elafontaine** [comment]
@pflong I understand that this is not a standard case, but still, in a deployment context where someone would be deploying both the mongo-exporter and the mongo on a server, if the first mongo in the list isn't available (e.g. roll-forward configs), then the whole thing fails to start.   I do not believe this is a desired behaviour in general, but probably linked to the mongo library used.
