### ISSUE TITLE
Using environment variables, startup errors 

### ISSUE THREAD

**Issue by xushiba** [percona/mongodb_exporter#763]
**Describe the bug**
When using multi-target collection, starting with an environment variable will report an error

**To Reproduce**
export MONGODB_USER=XXX
export MONGODB_PASSWORD=YYY
mongodb_exporter --mongodb.uri=mongodb://127.0.0.1:17001,mongodb://127.0.0.1:17001 

**Expected behavior**
But using this approach it's possible to：
mongodb_exporter --mongodb.uri=mongodb://user:pwd@127.0.0.1:17001,mongodb://user:pwd@127.0.0.1:17001 

**Logs**
Cannot connect to MongoDB: invalid dsn: error parsing uri: scheme must be \"mongodb\" or \"mongodb+srv\""

**Comment by pflong** [comment]
@xushiba What's your mongodb exporter version ?

**Comment by xushiba** [comment]
> @xushiba What's your mongodb exporter version ?

0.40

**Comment by xushiba** [comment]
Follow-up: MONGODB_USER varibales cannot be set to mongodb-xxx
