### ISSUE TITLE
ERRO[0000] Cannot connect to MongoDB: cannot connect to MongoDB: server at localhost:27017 reports wire version 5, but this version of the Go driver requires at least 6 (MongoDB 3.6)

### ISSUE THREAD

**Issue by tinyan-s** [percona/mongodb_exporter#802]
**Describe the bug**
If the issue relates to PMM, please open [JIRA PMM](https://jira.percona.com/projects/PMM/issues) issue instead of GH issue.

My Mongodb Version is 3.4.2, is support old mongo server version ？

**To Reproduce**
1. what parameters are being passed to `mongodb_exporter`
2. describe steps to reproduce the issue

./mongodb_exporter --mongodb.uri=mongodb://localhost:27017

**Expected behavior**

**Logs**
Please provide logs relevant to the issue

**Environment**
 - OS,
 - environment (docker, k8s, etc)
 - MongoDB version 3.4.2

**Additional context**

**Comment by BupycHuk** [comment]
Hi @tinyan-s, our mongodb_exporter supports only versions that's not EOLed yet. Mongo 3.4 EOL is January 2020, currently the oldest non-EOLed version is Mongo 5.
