### ISSUE TITLE
What does port 17001 used for?

### ISSUE THREAD

**Issue by Lisio** [percona/mongodb_exporter#809]
From readme:

```
docker run -d -p 9216:9216 -p 17001:17001 percona/mongodb_exporter:0.20 --mongodb.uri=mongodb://127.0.0.1:17001
```

Why should I expose container port 17001 which is already busy by mongodb?

**Comment by idoqo** [comment]
Hi @Lisio this looks like an oversight on our part, do you want to raise a PR to drop it?
