### ISSUE TITLE
Username Variable Overwrites part of connection string

### ISSUE THREAD

**Issue by yoUn3qcdi5dk6QiY6fpoQhttKvcC86jxSgedJek** [percona/mongodb_exporter#826]
**Describe the bug**
When trying to setup MongoDB exporter using variables for username and password as mentioned in the documentation, to not expose the password:
https://github.com/percona/mongodb_exporter?tab=readme-ov-file#mongodb-authentication
MONGODB_USER overwrites the **mongodb://** part of the connection-uri.
Using a connection-uri containing the username und password works without any issue.

**To Reproduce**
1. Either export both variables in bash directly and run the exporter in bahs or set them via Environment in systemd-file.
2. Exporter will not scrape any data, because it cannot access mongoDB because it has an invalid connection-uri.
3. Changing the variable "MONGODB_USER=username" to "MONGODB_USER=mongodb://username" makes the exporter work as expected with bash directly and Systemd

**Expected behavior**
MONGODB_USER should be able to be defined without "mongodb://"

**Environment**
 - Redhat 7/9
 - environment: native
 - MongoDB version 4.4.28,5.0.24
 - MongoDB-Exporter version: v0.40.4

**Comment by BupycHuk** [comment]
seems like this problem already fixed in #800

**Comment by yoUn3qcdi5dk6QiY6fpoQhttKvcC86jxSgedJek** [comment]
You are right, I did not see/associate this report with my problem.
In my case the username was "mongodb_exporter" and fits this previous bug report.
Close as this problem is already handled in https://github.com/percona/mongodb_exporter/pull/800
