### ISSUE TITLE
Missing Replica Set Metrics

### ISSUE THREAD

**Issue by eroji** [percona/mongodb_exporter#827]
**Describe the bug**
I currently have mongodb_exporter 0.40.0 installed with it connected against a replica set cluster. However, I don't see any metrics at all for replica set in the metrics endpoint. What am I missing?

**To Reproduce**
1. Install mongodb_exporter 0.40.0 with the following params for execution
```
MONGODB_URI=mongodb://127.0.0.1:27017/admin
MONGODB_USER=<user>
MONGODB_PASSWORD=<password>
OPTIONS="--collect-all --discovering-mode --compatible-mode"
```
3. Install MongoDB 7.0 and create the exporter user
4. Configure replica set
5. Navigate to `/metrics` endpoint for mongodb_exporter

**Expected behavior**
There should be metrics available for replica set

**Logs**
Please provide logs relevant to the issue

**Environment**
 - OS: AlmaLinux 9.2
 - environment (docker, k8s, etc): VM
 - MongoDB version: 7.0.7

**Additional context**

**Comment by du-do** [comment]
i get the same issue.  

`/metrics` get this metric :

`# HELP mongodb_up Whether MongoDB is up.
# TYPE mongodb_up gauge
mongodb_up 0
`

**Comment by igroene** [comment]
can you double check the exporter user has enough perms?
