### ISSUE TITLE
why so few metrics begin-with "mongodb"?but the dashboards use many metrics about "mongodb_"

### ISSUE THREAD

**Issue by meihaohui** [percona/mongodb_exporter#831]
![image](https://github.com/percona/mongodb_exporter/assets/30396241/6048940f-6bac-4fc4-8dea-63d97ecc0ae8)

**Comment by meihaohui** [comment]
even though i changed the version of mongodb and mongodb_exporter to the newest.

**Comment by meihaohui** [comment]
it's my command below
nohup ./mongodb_exporter --mongodb.uri=mongodb://admin:123456@127.0.0.1:27017 --compatible-mode &

**Comment by meihaohui** [comment]
when i append "--collect-all" to it further,
then it went wrong.
![image](https://github.com/percona/mongodb_exporter/assets/30396241/f46ed50d-a6c6-4e6a-8907-952c55be73b7)

**Comment by mostafabayat** [comment]
How did you fix it?

**Comment by meihaohui** [comment]
> How did you fix it?

The reason is that user admin is not root  .just userAdminAnyDatabase.
![image](https://github.com/percona/mongodb_exporter/assets/30396241/9b3ae9aa-7186-4d7c-8dca-7c916e653446)
![image](https://github.com/percona/mongodb_exporter/assets/30396241/eb8c1e6f-7769-46bc-bd42-f18931fe3c5d)
