### ISSUE TITLE
No metric mongodb_mongos_sharding_balancer_enabled for mongos

### ISSUE THREAD

**Issue by rkosyk** [percona/mongodb_exporter#847]
**Describe the bug**
mongodb_exporter v0.36.0 and above do not have metric `mongodb_mongos_sharding_balancer_enabled` for the mongos
This metric is used in percona MongoDB dashboard
https://github.com/percona/grafana-dashboards/blob/eeb453d5b8f6d122bb394e5f12aaa11500763055/dashboards/MongoDB/MongoDB_Cluster_Summary.json#L929

mongodb_exporter v0.35.0 and below have this metric

**To Reproduce**

1. what parameters are being passed to `mongodb_exporter`
```
image: bitnami/mongodb-exporter:0.36.0 
args:
  - --collect-all
  - --compatible-mode
```

**Expected behavior**
There is `mongodb_mongos_sharding_balancer_enabled` metric in mongodb_exporter v0.36.0 and above

**Logs**
When running mongodb_exporter logs in the debug mode I see this log record:
```
time="2024-04-30T08:39:36Z" level=debug msg="cannot create metric for balancer is enabled: mongo: no documents in result"
```

**Environment**
 - environment  k8s, 1.25
 - MongoDB versions: 4.4.13, 5.0.11

**Comment by rkosyk-dh-nf** [comment]
It looks like it has already been fixed in the new exporter version
https://github.com/percona/mongodb_exporter/pull/823

**Comment by rkosyk** [comment]
It looks like it has already been fixed in the new exporter version
https://github.com/percona/mongodb_exporter/pull/823
