### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by iokill** [percona/mongodb_exporter#883]
**Describe the bug**
It appears that the lastest release is from Nov 2023 and there have been quite some additions to the exporter since then. E.g. it now can expose shard metrics. Also, the official container image is still stuck on the last release 0.40.0 from 2023 which means these features are only available if one builds the `main` branch themselves.

It looks like using the official release will now (potentially) have security implications: https://github.com/percona/mongodb_exporter/issues/879

What are the plans to create a new release and if so when?

**To Reproduce**
1. Use latest release binary from GitHub or container image from Docker Hub with `--collector.shards`.

**Expected behavior**
New releases and container images being available.

**Comment by BupycHuk** [comment]
Hello @iokill we are planning to release 0.41.0 in the middle of august

**Comment by Deshke** [comment]
@BupycHuk did the release got pushed back ?

**Comment by cemakpolat** [comment]
is there any news for the new release? I see sharding metrics is now available in the main branch, but not in the released versions.

**Comment by BupycHuk** [comment]
Hi @iokill, @Deshke, @cemakpolat, we've just released v0.41.0, please check it.
