### ISSUE TITLE
Invalid DSN error for standard replica set connection string

### ISSUE THREAD

**Issue by wdonne** [percona/mongodb_exporter#887]
**Describe the bug**
When using a standard connection string for a MongoDB replica set like `mongodb://username:password@hostname-0,hostname-1,hostname-2`, the following error message appears in the logs:
"Cannot connect to MongoDB: invalid dsn: error parsing uri: scheme must be \"mongodb\" or \"mongodb+srv\""
**To Reproduce**
1. Create a secret with such a connection string
2. Use a `secretRef` to refer to it

**Expected behavior**
The connection to MongoDB should succeed.

**Logs**
"Cannot connect to MongoDB: invalid dsn: error parsing uri: scheme must be \"mongodb\" or \"mongodb+srv\""

**Environment**
 - OS: Amazon Linux 2
 - environment (docker, k8s, etc): EKS 1.29
 - MongoDB version: 7.0.11

**Additional context**
The example of a `mongodb+srv` URI in the documentation is wrong. Such a URI can't have multiple hosts or ports. It uses a DNS SRV record to discover all the members of a replica set. With the `mongodb` scheme, all the hosts of the replica set should be specified.

**Comment by BupycHuk** [comment]
Hi, what version of mongodb_exporter did you use? We haven't released mongodb_exporter with these changes yet.

**Comment by BupycHuk** [comment]
Hi @wdonne, we just release v0.41.0, please re-check it.
