### ISSUE TITLE
is it possible get the storageStats.wiredTiger and storageStats.indexDetails from $collStats

### ISSUE THREAD

**Issue by Marek1410** [percona/mongodb_exporter#897]
**Is your feature request related to a problem? Please describe.**
Find out more about current cache information (reads/writes) for specific collection and their indexes

**Describe the solution you'd like**
possible metrics like mongodb_collstats_storage_wt_xxx and for indexes respectively

**Comment by BupycHuk** [comment]
@Marek1410 could you please create a task in https://jira.percona.com/ ?

**Comment by Marek1410** [comment]
@BupycHuk sure, what project should i choose?

**Comment by BupycHuk** [comment]
Percona Monitoring and Management(I've seen that you already created a task)
