### ISSUE TITLE
MongoDB URI with ReplicaSet 

### ISSUE THREAD

**Issue by eman-cirrusgo** [percona/mongodb_exporter#901]
Hello, 

I keep getting the below error when using this Mongo URI <"mongodb://read:pwd@primary.internal:27017,secondary-1.internal:27017,secondary-2.internal:27017/?authSource=admin&replicaSet=replicaset-00">

```error
time="2024-08-28T10:50:30Z" level=error msg="Cannot connect to MongoDB: cannot connect to MongoDB: server selection error: server selection timeout, current topology: { Type: Single, Servers: [{ Addr: secondary-2.internal:27017, Type: Unknown }, ] }"

**Comment by adnull** [comment]
It is a known bug (https://github.com/percona/mongodb_exporter/issues/876) and we're waiting for the next release to get the fix be included into it.

**Comment by BupycHuk** [comment]
Hi @eman-cirrusgo, we just release v0.41.0, please check it there.

**Comment by Crash-1** [comment]
Hi,
Unfortunately, I don't know which version of the exporter the issue author reported but for me, it stopped working starting from version 0.41.0 (0.42.0 and 0.42.1 are also affected).

Startup log says:

`
time="2024-11-13T21:30:43Z" level=debug msg="Compatible mode: false"
time="2024-11-13T21:30:43Z" level=debug msg="Connection URI: mongodb://USER:PASSWORD@mongo-0.mongo:27017,mongo-2.mongo:27017,mongo-1.mongo:27017/?replicaSet=rs123"
time="2024-11-13T21:30:43Z" level=error msg="Cannot connect to MongoDB: invalid MongoDB options: a direct connection cannot be made if multiple hosts are specified"
`
