### ISSUE TITLE
0.41.1 Connections didn't closed

### ISSUE THREAD

**Issue by zxzharmlesszxz** [percona/mongodb_exporter#922]
**Describe the bug**
New exporter doesn't close connections and open files(fs-max) will be reached

**To Reproduce**
1. Install `mongodb_exporter` 0.41.1
2. Run `while true; do echo $(date -u +"%Y-%m-%d %H:%M:%S") $(sudo lsof -p $(pgrep -f mongodb_exporter) | wc -l); sleep 5; done` and you will see increases over all time

**Expected behavior**
Stable connection count.

**Logs**
No available extra logs

**Environment**
 - OS, Debian 11
 - environment (docker, k8s, etc)
 - MongoDB version 6.0.6

**Comment by BupycHuk** [comment]
Fix provided in 0.41.2
