### ISSUE TITLE
"failed to get PBM configuration" causes memory leak.

### ISSUE THREAD

**Issue by tidusstrife5** [percona/mongodb_exporter#927]
**Describe the bug**
Since the update that released the [following change](https://github.com/percona/mongodb_exporter/pull/866), we have seen the log below being constantly pushed AND the memory usage of the exporter continually ramps up (See screenshot below).

`failed to get PBM configuration: get: mongo: no documents in result`

![Screenshot 2024-10-07 at 2 22 49 PM](https://github.com/user-attachments/assets/1cdba5c1-1036-4d13-8336-a58d8dc17cc7)

**To Reproduce**
1. Use MongoDB 4.4 as a shard cluster
2. Use the collect-all parameter

**Expected behavior**
Memory is kept within safe boundaries AND/OR PBM config is not activated if it is not expected. (MongoDB 4.4 problem?)

**Logs**
failed to get PBM configuration: get: mongo: no documents in result

**Environment**
 - Flatcar
 - Docker
 - MongoDB 4.4 community edition

**Comment by idoqo** [comment]
Hi @tidusstrife5, thanks for your report - we are aware of this (https://github.com/percona/mongodb_exporter/issues/924) and are currently working on a fix.

**Comment by BupycHuk** [comment]
Fix provided in 0.41.2
