### ISSUE TITLE
not support option --split-cluster

### ISSUE THREAD

**Issue by nicknamenotknown** [percona/mongodb_exporter#930]
**Describe the bug**

**To Reproduce**
Run mongodb_exporter v0.41.2 with --split-cluster option
**Expected behavior**

**Logs**
mongodb_exporter: error: unknown flag --split-cluster

**Environment**
 - Linux,
 - k8s
 - MongoDB 6.0

**Additional context**

**Comment by BupycHuk** [comment]
Hi, this feature is not released yet.

**Comment by oh-nathaniel-bobrick** [comment]
@BupycHuk when is this feature going to be released?
