### ISSUE TITLE
Crash mongo with 0.41.2

### ISSUE THREAD

**Issue by phaedriel** [percona/mongodb_exporter#932]
Hi,

With exporter 0.41.2, my cluster mongo crash.
The number of tasks increase (visibility `systemctl status mongod`) and mongo crash with an error user.slice (more than 9989 tasks)

Running with service

```
#################################################################
# SERVICE MONGODB_EXPORTER (MANAGED BY PUPPET)
#################################################################
[Unit]
Description=Percona MongoDB Exporter
Before=shutdown.target
Wants=network-online.target
After=rsyslog.target network-online.target
Conflicts=shutdown.target

[Service]
# --------------------------------------- Configuration

# You can place environment variables in this file
EnvironmentFile=/etc/default/mongodb-exporter

# --------------------------------------- Lifecycle

Type=simple
ExecStart=/usr/local/bin/mongodb_exporter \
    --compatible-mode \
    --discovering-mode \
    --collect-all \
    --web.listen-address=0.0.0.0:9216 \
    --web.telemetry-path=/metrics

# --------------------------------------- Logging
SyslogIdentifier=mongodb_exporter

# --------------------------------------- Security
User=mongodb_exporter
Group=mongodb_exporter
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

/etc/default/mongodb-exporter

```
MONGODB_URI=mongodb://exporter:74c1a2*****6c3@127.0.0.1:27017/?authSource=admin&replicaSet=rs0
```

**Logs**

I noticed a lot of this message in my exporter logs

[2024-10-14 11:10:32] [info] time="2024-10-14T11:10:32+02:00" level=error msg="failed to create PBM client from uri mongodb://exporter:74c1a2*****6c3@127.0.0.1:27017/?authSource=admin&replicaSet=rs0: create mongo connection: ping: connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism \"SCRAM-SHA-256\": (AuthenticationFailed) Authentication failed." collector=pbm 

**Environment**

 - OS : debian 11
 - environment (docker, k8s, etc) : Vm (VmWare)
 - MongoDB version : 7.0.14-8 (percona distribution)
- PBM version : 2.7.0

**Additional context**

![image](https://github.com/user-attachments/assets/9bee6e1c-55ad-4be0-a79e-5bf4c3bf303d)

I stopped the exporter service (12:05) and change the command line.
With this new configuration, i don't have any problem. The number of tasks is stable.

```
ExecStart=/usr/local/bin/mongodb_exporter \
    --compatible-mode \
    --discovering-mode \
    --collector.currentopmetrics \
    --collector.dbstats \
    --collector.dbstatsfreestorage \
    --collector.diagnosticdata \
    --collector.fcv \
    --collector.replicasetstatus \
    --collector.topmetrics \
    --web.listen-address=0.0.0.0:9216 \
    --web.telemetry-path=/metrics
```

**Comment by idoqo** [comment]
This should be resolved in v0.42.0
