### ISSUE TITLE
mongodb_instance_uptime_seconds

### ISSUE THREAD

**Issue by kenytux** [percona/mongodb_exporter#947]
Hello,
I can't get certain metrics like "mongodb_instance_uptime_seconds" by going to localhost:9216/metrics.

Here my command:
'''
/usr/local/bin/mongodb_exporter --mongodb.uri=mongodb://user:password@localhost:27017/admin?ssl=false --collect-all
'''

And the metrics I get in the attached file
[metrics.txt](https://github.com/user-attachments/files/17631083/metrics.txt)

**Comment by BupycHuk** [comment]
to get that metric you need to enable compatible mode, new metric name is `mongodb_ss_uptime`

**Comment by kenytux** [comment]
It's work,
Thank you
