### ISSUE TITLE
Exporter 0.42.1 has recurring errors, does not export metrics

### ISSUE THREAD

**Issue by bpfoster** [percona/mongodb_exporter#970]
**Describe the bug**
After upgrading from mongodb_exporter 0.42.0 to 0.42.1, I am not getting many mongodb metrics exported.  In the exporter logs, I see nothing but the following line repeated over and over:
```
level=error msg="cannot retrieve engine type: Engine is unavailable" collector=diagnostic_data
```

If I downgrade the exporter back to 0.42.0, I see metrics again and that error is not in the logs.  Nothing other than the exporter version has changed.

**To Reproduce**
1. what parameters are being passed to `mongodb_exporter`
```
--collector.diagnosticdata --collector.replicasetstatus --collector.dbstats --compatible-mode --mongodb.direct-connect --mongodb.global-conn-pool --web.listen-address ":9216"
```

**Expected behavior**

**Logs**
See above

**Environment**
 - OS: debian 11
 - environment (docker, k8s, etc):  k8s
 - MongoDB version: 8.0.1

**Additional context**

**Comment by bpfoster** [comment]
The code in `main` looks good - looks looks like the changes to `diagnostic_data_collector` in this commit fixed things: https://github.com/percona/mongodb_exporter/commit/dc46ed5096dcf7394914730b4a42d1e59e7ab765#diff-f08bb8e2230b960e7f7941dbdf020e3aa607391de1dc0f8683c315265d77b2f6R120.

Can you create a new release including this?

**Comment by BupycHuk** [comment]
Hello @bpfoster, 0.42.1 release was done by mistake. We've already removed i from everywhere, but seems like a few hours ago some automation created all images again. Please use 0.42.0 for now, we will release 0.43.0 within a few days.

**Comment by bpfoster** [comment]
Ok great, thank you!  Will roll back to 0.42.0.
