### ISSUE TITLE
Is there any reference where we can find the kubernetes compatibility versions for specific mongo operator? 

### ISSUE THREAD

**Issue by Sandhyaranitp** [percona/mongodb_exporter#978]
I'm looking for information on the Kubernetes version compatibility for Operator version 0.7.5.1. Specifically, I need to know which Kubernetes versions (within the 1.2x to 1.x range) are supported by this operator version. Could anyone provide a reference or documentation that outlines this?

**Comment by BupycHuk** [comment]
Hello @Sandhyaranitp, this repository is about mongodb_exporter. Probably you are looking for https://github.com/percona/percona-server-mongodb-operator.

**Comment by Sandhyaranitp** [comment]
Hi @BupycHuk , yes looking for mongo operator, do we have any reference for Kubernetes supported version for mongo operator 0.7.5.1.?

**Comment by BupycHuk** [comment]
@Sandhyaranitp It's better to ask in that repository
