### ISSUE TITLE
could all metrics add appName label ？

### ISSUE THREAD

**Issue by jixinzhang001** [percona/mongodb_exporter#981]
Some apps connect same mongo cluster，I want to know every app qps/tps and connection from correlative metrics。

client(apps) setting : mongodb://user:password@test.mongo.com/?readPreference=secondaryPreferred&appName=modulename

If this functionality can be implemented, it will allow us to understand the usage of MongoDB by each client. This way, when there is an abnormal trend in MongoDB, we can quickly identify which client is causing it, greatly contributing to business stability.

**Comment by BupycHuk** [comment]
Hi, unfortunately it's not possible from exporter side, we have a product called [PMM](https://github.com/percona/pmm) with Query Analytics feature where we are planning to add this information.
